packages:
  - "packages/plugins/*"
  - "packages/cli"
  - "packages/check-schema"
  - "packages/logger"
injectWorkspacePackages: true
allowBuilds:
  '@google/genai': true
  esbuild: true
  koffi: true
  msgpackr-extract: true
  protobufjs: true
