packages:
  - 'packages/cli'
  - 'packages/web'
  - 'packages/plugin-pi'
  - 'packages/plugin-opencode'
  - 'tools/build'
injectWorkspacePackages: true
allowBuilds:
  '@google/genai': true
  esbuild: true
  koffi: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
