packages:
  - "packages/plugins/*"
  - "packages/cli"
  - "packages/check-schema"

allowBuilds:
  '@google/genai': true
  better-sqlite3: false
  esbuild: true
  koffi: false
  msgpackr-extract: false
  protobufjs: false
