// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ApiVersion.
const (
	V1 ApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the ApiVersion enum.
func (e ApiVersion) Valid() bool {
	switch e {
	case V1:
		return true
	default:
		return false
	}
}

// Defines values for Bucket.
const (
	BucketDay   Bucket = "day"
	BucketMonth Bucket = "month"
	BucketWeek  Bucket = "week"
	BucketYear  Bucket = "year"
)

// Valid indicates whether the value is a known member of the Bucket enum.
func (e Bucket) Valid() bool {
	switch e {
	case BucketDay:
		return true
	case BucketMonth:
		return true
	case BucketWeek:
		return true
	case BucketYear:
		return true
	default:
		return false
	}
}

// Defines values for Capability.
const (
	Facets    Capability = "facets"
	Ingestion Capability = "ingestion"
	Usage     Capability = "usage"
)

// Valid indicates whether the value is a known member of the Capability enum.
func (e Capability) Valid() bool {
	switch e {
	case Facets:
		return true
	case Ingestion:
		return true
	case Usage:
		return true
	default:
		return false
	}
}

// Defines values for CollectorAttemptErrorCode.
const (
	Cancelled        CollectorAttemptErrorCode = "cancelled"
	CollectionFailed CollectorAttemptErrorCode = "collection_failed"
	PublisherLost    CollectorAttemptErrorCode = "publisher_lost"
	SubmissionFailed CollectorAttemptErrorCode = "submission_failed"
)

// Valid indicates whether the value is a known member of the CollectorAttemptErrorCode enum.
func (e CollectorAttemptErrorCode) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case CollectionFailed:
		return true
	case PublisherLost:
		return true
	case SubmissionFailed:
		return true
	default:
		return false
	}
}

// Defines values for CollectorAttemptHarnesses.
const (
	CollectorAttemptHarnessesComplete CollectorAttemptHarnesses = "complete"
	CollectorAttemptHarnessesFailed   CollectorAttemptHarnesses = "failed"
	CollectorAttemptHarnessesRunning  CollectorAttemptHarnesses = "running"
	CollectorAttemptHarnessesSkipped  CollectorAttemptHarnesses = "skipped"
	CollectorAttemptHarnessesWaiting  CollectorAttemptHarnesses = "waiting"
)

// Valid indicates whether the value is a known member of the CollectorAttemptHarnesses enum.
func (e CollectorAttemptHarnesses) Valid() bool {
	switch e {
	case CollectorAttemptHarnessesComplete:
		return true
	case CollectorAttemptHarnessesFailed:
		return true
	case CollectorAttemptHarnessesRunning:
		return true
	case CollectorAttemptHarnessesSkipped:
		return true
	case CollectorAttemptHarnessesWaiting:
		return true
	default:
		return false
	}
}

// Defines values for CollectorAttemptStage.
const (
	CollectorAttemptStageAccepted    CollectorAttemptStage = "accepted"
	CollectorAttemptStageCapturing   CollectorAttemptStage = "capturing"
	CollectorAttemptStageFailed      CollectorAttemptStage = "failed"
	CollectorAttemptStageInterrupted CollectorAttemptStage = "interrupted"
	CollectorAttemptStageSubmitting  CollectorAttemptStage = "submitting"
	CollectorAttemptStageWaiting     CollectorAttemptStage = "waiting"
)

// Valid indicates whether the value is a known member of the CollectorAttemptStage enum.
func (e CollectorAttemptStage) Valid() bool {
	switch e {
	case CollectorAttemptStageAccepted:
		return true
	case CollectorAttemptStageCapturing:
		return true
	case CollectorAttemptStageFailed:
		return true
	case CollectorAttemptStageInterrupted:
		return true
	case CollectorAttemptStageSubmitting:
		return true
	case CollectorAttemptStageWaiting:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeInternalError    ErrorCode = "internal_error"
	ErrorCodeInvalidRequest   ErrorCode = "invalid_request"
	ErrorCodeMethodNotAllowed ErrorCode = "method_not_allowed"
	ErrorCodeNotFound         ErrorCode = "not_found"
	ErrorCodeUnavailable      ErrorCode = "unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeMethodNotAllowed:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceOutcomeDisposition.
const (
	EvidenceOutcomeDispositionAmbiguous  EvidenceOutcomeDisposition = "ambiguous"
	EvidenceOutcomeDispositionContext    EvidenceOutcomeDisposition = "context"
	EvidenceOutcomeDispositionDuplicate  EvidenceOutcomeDisposition = "duplicate"
	EvidenceOutcomeDispositionPending    EvidenceOutcomeDisposition = "pending"
	EvidenceOutcomeDispositionProcessed  EvidenceOutcomeDisposition = "processed"
	EvidenceOutcomeDispositionSuperseded EvidenceOutcomeDisposition = "superseded"
)

// Valid indicates whether the value is a known member of the EvidenceOutcomeDisposition enum.
func (e EvidenceOutcomeDisposition) Valid() bool {
	switch e {
	case EvidenceOutcomeDispositionAmbiguous:
		return true
	case EvidenceOutcomeDispositionContext:
		return true
	case EvidenceOutcomeDispositionDuplicate:
		return true
	case EvidenceOutcomeDispositionPending:
		return true
	case EvidenceOutcomeDispositionProcessed:
		return true
	case EvidenceOutcomeDispositionSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for ExtractionDiagnostic.
const (
	FieldLimit            ExtractionDiagnostic = "field_limit"
	InvalidFieldType      ExtractionDiagnostic = "invalid_field_type"
	NativeSubagentPresent ExtractionDiagnostic = "native_subagent_present"
	UnsafeMetadata        ExtractionDiagnostic = "unsafe_metadata"
)

// Valid indicates whether the value is a known member of the ExtractionDiagnostic enum.
func (e ExtractionDiagnostic) Valid() bool {
	switch e {
	case FieldLimit:
		return true
	case InvalidFieldType:
		return true
	case NativeSubagentPresent:
		return true
	case UnsafeMetadata:
		return true
	default:
		return false
	}
}

// Defines values for Harness.
const (
	ClaudeCode Harness = "claude-code"
	Codex      Harness = "codex"
	Opencode   Harness = "opencode"
	Pi         Harness = "pi"
)

// Valid indicates whether the value is a known member of the Harness enum.
func (e Harness) Valid() bool {
	switch e {
	case ClaudeCode:
		return true
	case Codex:
		return true
	case Opencode:
		return true
	case Pi:
		return true
	default:
		return false
	}
}

// Defines values for HarnessSyncStatus.
const (
	HarnessSyncStatusDiscovering HarnessSyncStatus = "discovering"
	HarnessSyncStatusFailed      HarnessSyncStatus = "failed"
	HarnessSyncStatusNormalizing HarnessSyncStatus = "normalizing"
	HarnessSyncStatusPending     HarnessSyncStatus = "pending"
	HarnessSyncStatusSkipped     HarnessSyncStatus = "skipped"
	HarnessSyncStatusSynced      HarnessSyncStatus = "synced"
	HarnessSyncStatusSyncing     HarnessSyncStatus = "syncing"
)

// Valid indicates whether the value is a known member of the HarnessSyncStatus enum.
func (e HarnessSyncStatus) Valid() bool {
	switch e {
	case HarnessSyncStatusDiscovering:
		return true
	case HarnessSyncStatusFailed:
		return true
	case HarnessSyncStatusNormalizing:
		return true
	case HarnessSyncStatusPending:
		return true
	case HarnessSyncStatusSkipped:
		return true
	case HarnessSyncStatusSynced:
		return true
	case HarnessSyncStatusSyncing:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesIdentityVersion.
const (
	IngestionCapabilitiesIdentityVersionN1 IngestionCapabilitiesIdentityVersion = 1
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesIdentityVersion enum.
func (e IngestionCapabilitiesIdentityVersion) Valid() bool {
	switch e {
	case IngestionCapabilitiesIdentityVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxBodyBytes.
const (
	IngestionCapabilitiesMaxBodyBytesN1048576e06 IngestionCapabilitiesMaxBodyBytes = 1.048576e+06
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxBodyBytes enum.
func (e IngestionCapabilitiesMaxBodyBytes) Valid() bool {
	switch e {
	case IngestionCapabilitiesMaxBodyBytesN1048576e06:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxEntries.
const (
	IngestionCapabilitiesMaxEntriesN256 IngestionCapabilitiesMaxEntries = 256
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxEntries enum.
func (e IngestionCapabilitiesMaxEntries) Valid() bool {
	switch e {
	case IngestionCapabilitiesMaxEntriesN256:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxInteger.
const (
	N9007199254740991e15 IngestionCapabilitiesMaxInteger = 9.007199254740991e+15
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxInteger enum.
func (e IngestionCapabilitiesMaxInteger) Valid() bool {
	switch e {
	case N9007199254740991e15:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxStringBytes.
const (
	IngestionCapabilitiesMaxStringBytesN256 IngestionCapabilitiesMaxStringBytes = 256
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxStringBytes enum.
func (e IngestionCapabilitiesMaxStringBytes) Valid() bool {
	switch e {
	case IngestionCapabilitiesMaxStringBytesN256:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesProtocolVersion.
const (
	IngestionCapabilitiesProtocolVersionN1 IngestionCapabilitiesProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesProtocolVersion enum.
func (e IngestionCapabilitiesProtocolVersion) Valid() bool {
	switch e {
	case IngestionCapabilitiesProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesSemanticsVersion.
const (
	IngestionCapabilitiesSemanticsVersionN1 IngestionCapabilitiesSemanticsVersion = 1
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesSemanticsVersion enum.
func (e IngestionCapabilitiesSemanticsVersion) Valid() bool {
	switch e {
	case IngestionCapabilitiesSemanticsVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for InstanceResponseDataReadiness.
const (
	InstanceResponseDataReadinessMetadata    InstanceResponseDataReadiness = "metadata"
	InstanceResponseDataReadinessReady       InstanceResponseDataReadiness = "ready"
	InstanceResponseDataReadinessRebuild     InstanceResponseDataReadiness = "rebuild"
	InstanceResponseDataReadinessRecovery    InstanceResponseDataReadiness = "recovery"
	InstanceResponseDataReadinessUnavailable InstanceResponseDataReadiness = "unavailable"
)

// Valid indicates whether the value is a known member of the InstanceResponseDataReadiness enum.
func (e InstanceResponseDataReadiness) Valid() bool {
	switch e {
	case InstanceResponseDataReadinessMetadata:
		return true
	case InstanceResponseDataReadinessReady:
		return true
	case InstanceResponseDataReadinessRebuild:
		return true
	case InstanceResponseDataReadinessRecovery:
		return true
	case InstanceResponseDataReadinessUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for InstanceResponseV2ApiVersion.
const (
	V2 InstanceResponseV2ApiVersion = "v2"
)

// Valid indicates whether the value is a known member of the InstanceResponseV2ApiVersion enum.
func (e InstanceResponseV2ApiVersion) Valid() bool {
	switch e {
	case V2:
		return true
	default:
		return false
	}
}

// Defines values for InstanceResponseV2DataReadiness.
const (
	InstanceResponseV2DataReadinessMetadata    InstanceResponseV2DataReadiness = "metadata"
	InstanceResponseV2DataReadinessReady       InstanceResponseV2DataReadiness = "ready"
	InstanceResponseV2DataReadinessRebuild     InstanceResponseV2DataReadiness = "rebuild"
	InstanceResponseV2DataReadinessRecovery    InstanceResponseV2DataReadiness = "recovery"
	InstanceResponseV2DataReadinessUnavailable InstanceResponseV2DataReadiness = "unavailable"
)

// Valid indicates whether the value is a known member of the InstanceResponseV2DataReadiness enum.
func (e InstanceResponseV2DataReadiness) Valid() bool {
	switch e {
	case InstanceResponseV2DataReadinessMetadata:
		return true
	case InstanceResponseV2DataReadinessReady:
		return true
	case InstanceResponseV2DataReadinessRebuild:
		return true
	case InstanceResponseV2DataReadinessRecovery:
		return true
	case InstanceResponseV2DataReadinessUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for InstanceResponseV2Permissions.
const (
	Ingest InstanceResponseV2Permissions = "ingest"
	Read   InstanceResponseV2Permissions = "read"
)

// Valid indicates whether the value is a known member of the InstanceResponseV2Permissions enum.
func (e InstanceResponseV2Permissions) Valid() bool {
	switch e {
	case Ingest:
		return true
	case Read:
		return true
	default:
		return false
	}
}

// Defines values for InstanceResponseV2ServerKind.
const (
	Hosted   InstanceResponseV2ServerKind = "hosted"
	Personal InstanceResponseV2ServerKind = "personal"
)

// Valid indicates whether the value is a known member of the InstanceResponseV2ServerKind enum.
func (e InstanceResponseV2ServerKind) Valid() bool {
	switch e {
	case Hosted:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// Defines values for LocationGroup.
const (
	Directory  LocationGroup = "directory"
	Repository LocationGroup = "repository"
)

// Valid indicates whether the value is a known member of the LocationGroup enum.
func (e LocationGroup) Valid() bool {
	switch e {
	case Directory:
		return true
	case Repository:
		return true
	default:
		return false
	}
}

// Defines values for Period.
const (
	PeriodAll       Period = "all"
	PeriodMonth     Period = "month"
	PeriodToday     Period = "today"
	PeriodWeek      Period = "week"
	PeriodYear      Period = "year"
	PeriodYesterday Period = "yesterday"
)

// Valid indicates whether the value is a known member of the Period enum.
func (e Period) Valid() bool {
	switch e {
	case PeriodAll:
		return true
	case PeriodMonth:
		return true
	case PeriodToday:
		return true
	case PeriodWeek:
		return true
	case PeriodYear:
		return true
	case PeriodYesterday:
		return true
	default:
		return false
	}
}

// Defines values for PublicationBatchIdentityVersion.
const (
	PublicationBatchIdentityVersionN1 PublicationBatchIdentityVersion = 1
)

// Valid indicates whether the value is a known member of the PublicationBatchIdentityVersion enum.
func (e PublicationBatchIdentityVersion) Valid() bool {
	switch e {
	case PublicationBatchIdentityVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for PublicationBatchProtocolVersion.
const (
	PublicationBatchProtocolVersionN1 PublicationBatchProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the PublicationBatchProtocolVersion enum.
func (e PublicationBatchProtocolVersion) Valid() bool {
	switch e {
	case PublicationBatchProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for PublicationBatchSemanticsVersion.
const (
	PublicationBatchSemanticsVersionN1 PublicationBatchSemanticsVersion = 1
)

// Valid indicates whether the value is a known member of the PublicationBatchSemanticsVersion enum.
func (e PublicationBatchSemanticsVersion) Valid() bool {
	switch e {
	case PublicationBatchSemanticsVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for PublicationFactProviderSource.
const (
	Explicit PublicationFactProviderSource = "explicit"
	Inferred PublicationFactProviderSource = "inferred"
	Unknown  PublicationFactProviderSource = "unknown"
)

// Valid indicates whether the value is a known member of the PublicationFactProviderSource enum.
func (e PublicationFactProviderSource) Valid() bool {
	switch e {
	case Explicit:
		return true
	case Inferred:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for PublicationFactQuality.
const (
	PublicationFactQualityDerived   PublicationFactQuality = "derived"
	PublicationFactQualityEstimated PublicationFactQuality = "estimated"
	PublicationFactQualityExact     PublicationFactQuality = "exact"
)

// Valid indicates whether the value is a known member of the PublicationFactQuality enum.
func (e PublicationFactQuality) Valid() bool {
	switch e {
	case PublicationFactQualityDerived:
		return true
	case PublicationFactQualityEstimated:
		return true
	case PublicationFactQualityExact:
		return true
	default:
		return false
	}
}

// Defines values for PublicationFactUsageScope.
const (
	Message PublicationFactUsageScope = "message"
)

// Valid indicates whether the value is a known member of the PublicationFactUsageScope enum.
func (e PublicationFactUsageScope) Valid() bool {
	switch e {
	case Message:
		return true
	default:
		return false
	}
}

// Defines values for PublicationRevisionRule.
const (
	ClaudeSourceTimestampV1 PublicationRevisionRule = "claude-source-timestamp-v1"
)

// Valid indicates whether the value is a known member of the PublicationRevisionRule enum.
func (e PublicationRevisionRule) Valid() bool {
	switch e {
	case ClaudeSourceTimestampV1:
		return true
	default:
		return false
	}
}

// Defines values for RawBatchExtractorVersion.
const (
	RawBatchExtractorVersionN1 RawBatchExtractorVersion = 1
)

// Valid indicates whether the value is a known member of the RawBatchExtractorVersion enum.
func (e RawBatchExtractorVersion) Valid() bool {
	switch e {
	case RawBatchExtractorVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for RawBatchProtocolVersion.
const (
	RawBatchProtocolVersionN2 RawBatchProtocolVersion = 2
)

// Valid indicates whether the value is a known member of the RawBatchProtocolVersion enum.
func (e RawBatchProtocolVersion) Valid() bool {
	switch e {
	case RawBatchProtocolVersionN2:
		return true
	default:
		return false
	}
}

// Defines values for RawBatchV3ExtractorVersion.
const (
	RawBatchV3ExtractorVersionN1 RawBatchV3ExtractorVersion = 1
)

// Valid indicates whether the value is a known member of the RawBatchV3ExtractorVersion enum.
func (e RawBatchV3ExtractorVersion) Valid() bool {
	switch e {
	case RawBatchV3ExtractorVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for RawBatchV3ProtocolVersion.
const (
	RawBatchV3ProtocolVersionN3 RawBatchV3ProtocolVersion = 3
)

// Valid indicates whether the value is a known member of the RawBatchV3ProtocolVersion enum.
func (e RawBatchV3ProtocolVersion) Valid() bool {
	switch e {
	case RawBatchV3ProtocolVersionN3:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesCompletion.
const (
	RawCapabilitiesCompletionAcceptance RawCapabilitiesCompletion = "acceptance"
)

// Valid indicates whether the value is a known member of the RawCapabilitiesCompletion enum.
func (e RawCapabilitiesCompletion) Valid() bool {
	switch e {
	case RawCapabilitiesCompletionAcceptance:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesDatasetId.
const (
	RawCapabilitiesDatasetIdDefault RawCapabilitiesDatasetId = "default"
)

// Valid indicates whether the value is a known member of the RawCapabilitiesDatasetId enum.
func (e RawCapabilitiesDatasetId) Valid() bool {
	switch e {
	case RawCapabilitiesDatasetIdDefault:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesExtractorVersion.
const (
	RawCapabilitiesExtractorVersionN1 RawCapabilitiesExtractorVersion = 1
)

// Valid indicates whether the value is a known member of the RawCapabilitiesExtractorVersion enum.
func (e RawCapabilitiesExtractorVersion) Valid() bool {
	switch e {
	case RawCapabilitiesExtractorVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesMaxBodyBytes.
const (
	RawCapabilitiesMaxBodyBytesN1048576e06 RawCapabilitiesMaxBodyBytes = 1.048576e+06
)

// Valid indicates whether the value is a known member of the RawCapabilitiesMaxBodyBytes enum.
func (e RawCapabilitiesMaxBodyBytes) Valid() bool {
	switch e {
	case RawCapabilitiesMaxBodyBytesN1048576e06:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesMaxEntries.
const (
	RawCapabilitiesMaxEntriesN256 RawCapabilitiesMaxEntries = 256
)

// Valid indicates whether the value is a known member of the RawCapabilitiesMaxEntries enum.
func (e RawCapabilitiesMaxEntries) Valid() bool {
	switch e {
	case RawCapabilitiesMaxEntriesN256:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesProtocolVersion.
const (
	RawCapabilitiesProtocolVersionN2 RawCapabilitiesProtocolVersion = 2
)

// Valid indicates whether the value is a known member of the RawCapabilitiesProtocolVersion enum.
func (e RawCapabilitiesProtocolVersion) Valid() bool {
	switch e {
	case RawCapabilitiesProtocolVersionN2:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesV3Completion.
const (
	RawCapabilitiesV3CompletionAcceptance RawCapabilitiesV3Completion = "acceptance"
)

// Valid indicates whether the value is a known member of the RawCapabilitiesV3Completion enum.
func (e RawCapabilitiesV3Completion) Valid() bool {
	switch e {
	case RawCapabilitiesV3CompletionAcceptance:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesV3ExtractorVersion.
const (
	RawCapabilitiesV3ExtractorVersionN1 RawCapabilitiesV3ExtractorVersion = 1
)

// Valid indicates whether the value is a known member of the RawCapabilitiesV3ExtractorVersion enum.
func (e RawCapabilitiesV3ExtractorVersion) Valid() bool {
	switch e {
	case RawCapabilitiesV3ExtractorVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesV3MaxBodyBytes.
const (
	RawCapabilitiesV3MaxBodyBytesN1048576e06 RawCapabilitiesV3MaxBodyBytes = 1.048576e+06
)

// Valid indicates whether the value is a known member of the RawCapabilitiesV3MaxBodyBytes enum.
func (e RawCapabilitiesV3MaxBodyBytes) Valid() bool {
	switch e {
	case RawCapabilitiesV3MaxBodyBytesN1048576e06:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesV3MaxEntries.
const (
	RawCapabilitiesV3MaxEntriesN256 RawCapabilitiesV3MaxEntries = 256
)

// Valid indicates whether the value is a known member of the RawCapabilitiesV3MaxEntries enum.
func (e RawCapabilitiesV3MaxEntries) Valid() bool {
	switch e {
	case RawCapabilitiesV3MaxEntriesN256:
		return true
	default:
		return false
	}
}

// Defines values for RawCapabilitiesV3ProtocolVersion.
const (
	RawCapabilitiesV3ProtocolVersionN3 RawCapabilitiesV3ProtocolVersion = 3
)

// Valid indicates whether the value is a known member of the RawCapabilitiesV3ProtocolVersion enum.
func (e RawCapabilitiesV3ProtocolVersion) Valid() bool {
	switch e {
	case RawCapabilitiesV3ProtocolVersionN3:
		return true
	default:
		return false
	}
}

// Defines values for RawReceiptDatasetId.
const (
	RawReceiptDatasetIdDefault RawReceiptDatasetId = "default"
)

// Valid indicates whether the value is a known member of the RawReceiptDatasetId enum.
func (e RawReceiptDatasetId) Valid() bool {
	switch e {
	case RawReceiptDatasetIdDefault:
		return true
	default:
		return false
	}
}

// Defines values for RawRecordFormat.
const (
	ClaudeCodeJsonl RawRecordFormat = "claude-code-jsonl"
	CodexJsonl      RawRecordFormat = "codex-jsonl"
	OpencodeProject RawRecordFormat = "opencode-project"
	OpencodeSession RawRecordFormat = "opencode-session"
	OpencodeV1      RawRecordFormat = "opencode-v1"
	OpencodeV2      RawRecordFormat = "opencode-v2"
	PiJsonl         RawRecordFormat = "pi-jsonl"
)

// Valid indicates whether the value is a known member of the RawRecordFormat enum.
func (e RawRecordFormat) Valid() bool {
	switch e {
	case ClaudeCodeJsonl:
		return true
	case CodexJsonl:
		return true
	case OpencodeProject:
		return true
	case OpencodeSession:
		return true
	case OpencodeV1:
		return true
	case OpencodeV2:
		return true
	case PiJsonl:
		return true
	default:
		return false
	}
}

// Defines values for SortDirection.
const (
	Asc  SortDirection = "asc"
	Desc SortDirection = "desc"
)

// Valid indicates whether the value is a known member of the SortDirection enum.
func (e SortDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for SortField.
const (
	SortFieldAverageContext SortField = "averageContext"
	SortFieldCacheRead      SortField = "cacheRead"
	SortFieldCacheWrite     SortField = "cacheWrite"
	SortFieldContext        SortField = "context"
	SortFieldDate           SortField = "date"
	SortFieldHarness        SortField = "harness"
	SortFieldInput          SortField = "input"
	SortFieldMaxContext     SortField = "maxContext"
	SortFieldMedianContext  SortField = "medianContext"
	SortFieldModel          SortField = "model"
	SortFieldName           SortField = "name"
	SortFieldOutput         SortField = "output"
	SortFieldProvider       SortField = "provider"
	SortFieldReasoning      SortField = "reasoning"
	SortFieldSessions       SortField = "sessions"
	SortFieldTotal          SortField = "total"
)

// Valid indicates whether the value is a known member of the SortField enum.
func (e SortField) Valid() bool {
	switch e {
	case SortFieldAverageContext:
		return true
	case SortFieldCacheRead:
		return true
	case SortFieldCacheWrite:
		return true
	case SortFieldContext:
		return true
	case SortFieldDate:
		return true
	case SortFieldHarness:
		return true
	case SortFieldInput:
		return true
	case SortFieldMaxContext:
		return true
	case SortFieldMedianContext:
		return true
	case SortFieldModel:
		return true
	case SortFieldName:
		return true
	case SortFieldOutput:
		return true
	case SortFieldProvider:
		return true
	case SortFieldReasoning:
		return true
	case SortFieldSessions:
		return true
	case SortFieldTotal:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseV2DataReadiness.
const (
	StatusResponseV2DataReadinessMetadata    StatusResponseV2DataReadiness = "metadata"
	StatusResponseV2DataReadinessReady       StatusResponseV2DataReadiness = "ready"
	StatusResponseV2DataReadinessRebuild     StatusResponseV2DataReadiness = "rebuild"
	StatusResponseV2DataReadinessRecovery    StatusResponseV2DataReadiness = "recovery"
	StatusResponseV2DataReadinessUnavailable StatusResponseV2DataReadiness = "unavailable"
)

// Valid indicates whether the value is a known member of the StatusResponseV2DataReadiness enum.
func (e StatusResponseV2DataReadiness) Valid() bool {
	switch e {
	case StatusResponseV2DataReadinessMetadata:
		return true
	case StatusResponseV2DataReadinessReady:
		return true
	case StatusResponseV2DataReadinessRebuild:
		return true
	case StatusResponseV2DataReadinessRecovery:
		return true
	case StatusResponseV2DataReadinessUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for SyncPhase.
const (
	SyncPhaseReady SyncPhase = "ready"
)

// Valid indicates whether the value is a known member of the SyncPhase enum.
func (e SyncPhase) Valid() bool {
	switch e {
	case SyncPhaseReady:
		return true
	default:
		return false
	}
}

// Defines values for SyncResponseDataReadiness.
const (
	SyncResponseDataReadinessMetadata    SyncResponseDataReadiness = "metadata"
	SyncResponseDataReadinessReady       SyncResponseDataReadiness = "ready"
	SyncResponseDataReadinessRebuild     SyncResponseDataReadiness = "rebuild"
	SyncResponseDataReadinessRecovery    SyncResponseDataReadiness = "recovery"
	SyncResponseDataReadinessUnavailable SyncResponseDataReadiness = "unavailable"
)

// Valid indicates whether the value is a known member of the SyncResponseDataReadiness enum.
func (e SyncResponseDataReadiness) Valid() bool {
	switch e {
	case SyncResponseDataReadinessMetadata:
		return true
	case SyncResponseDataReadinessReady:
		return true
	case SyncResponseDataReadinessRebuild:
		return true
	case SyncResponseDataReadinessRecovery:
		return true
	case SyncResponseDataReadinessUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for UsageQuality.
const (
	UsageQualityConfirmed UsageQuality = "confirmed"
	UsageQualityEstimated UsageQuality = "estimated"
)

// Valid indicates whether the value is a known member of the UsageQuality enum.
func (e UsageQuality) Valid() bool {
	switch e {
	case UsageQualityConfirmed:
		return true
	case UsageQualityEstimated:
		return true
	default:
		return false
	}
}

// Defines values for UsageTab.
const (
	UsageTabContext   UsageTab = "context"
	UsageTabHarnesses UsageTab = "harnesses"
	UsageTabModels    UsageTab = "models"
	UsageTabProviders UsageTab = "providers"
	UsageTabRepo      UsageTab = "repo"
	UsageTabSessions  UsageTab = "sessions"
	UsageTabTokens    UsageTab = "tokens"
)

// Valid indicates whether the value is a known member of the UsageTab enum.
func (e UsageTab) Valid() bool {
	switch e {
	case UsageTabContext:
		return true
	case UsageTabHarnesses:
		return true
	case UsageTabModels:
		return true
	case UsageTabProviders:
		return true
	case UsageTabRepo:
		return true
	case UsageTabSessions:
		return true
	case UsageTabTokens:
		return true
	default:
		return false
	}
}

// ApiVersion defines model for ApiVersion.
type ApiVersion string

// BrowserSessionRequest defines model for BrowserSessionRequest.
type BrowserSessionRequest struct {
	Token string `json:"token"`
}

// Bucket defines model for Bucket.
type Bucket string

// Capability defines model for Capability.
type Capability string

// CollectorAttempt defines model for CollectorAttempt.
type CollectorAttempt struct {
	AcknowledgedBatches Count                      `json:"acknowledgedBatches"`
	AcknowledgedEntries Count                      `json:"acknowledgedEntries"`
	AttemptId           string                     `json:"attemptId"`
	ErrorCode           *CollectorAttemptErrorCode `json:"errorCode,omitempty"`

	// ExpiresAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	ExpiresAtMs TimestampMs `json:"expiresAtMs"`

	// FinishedAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	FinishedAtMs *TimestampMs                         `json:"finishedAtMs,omitempty"`
	Harnesses    map[string]CollectorAttemptHarnesses `json:"harnesses"`
	Pending      Count                                `json:"pending"`
	PendingKnown bool                                 `json:"pendingKnown"`
	Stage        CollectorAttemptStage                `json:"stage"`

	// StartedAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	StartedAtMs TimestampMs `json:"startedAtMs"`

	// UpdatedAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	UpdatedAtMs TimestampMs `json:"updatedAtMs"`
}

// CollectorAttemptErrorCode defines model for CollectorAttempt.ErrorCode.
type CollectorAttemptErrorCode string

// CollectorAttemptHarnesses defines model for CollectorAttempt.Harnesses.
type CollectorAttemptHarnesses string

// CollectorAttemptStage defines model for CollectorAttempt.Stage.
type CollectorAttemptStage string

// CollectorProgressResponse defines model for CollectorProgressResponse.
type CollectorProgressResponse struct {
	Attempts   []CollectorAttempt `json:"attempts"`
	InstanceId string             `json:"instanceId"`
}

// Count defines model for Count.
type Count = int64

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// EvidenceOutcome defines model for EvidenceOutcome.
type EvidenceOutcome struct {
	Code          *string                    `json:"code,omitempty"`
	Disposition   EvidenceOutcomeDisposition `json:"disposition"`
	EvidenceId    string                     `json:"evidenceId"`
	FactId        *string                    `json:"factId,omitempty"`
	Generation    Count                      `json:"generation"`
	InputRevision Count                      `json:"inputRevision"`
}

// EvidenceOutcomeDisposition defines model for EvidenceOutcome.Disposition.
type EvidenceOutcomeDisposition string

// ExtractionDiagnostic defines model for ExtractionDiagnostic.
type ExtractionDiagnostic string

// Harness defines model for Harness.
type Harness string

// HarnessSyncStatus defines model for HarnessSyncStatus.
type HarnessSyncStatus string

// IngestionCapabilities defines model for IngestionCapabilities.
type IngestionCapabilities struct {
	// DatabaseId At most 256 UTF-8 bytes; no control characters.
	DatabaseId       string                                `json:"databaseId"`
	IdentityVersion  IngestionCapabilitiesIdentityVersion  `json:"identityVersion"`
	MaxBodyBytes     IngestionCapabilitiesMaxBodyBytes     `json:"maxBodyBytes"`
	MaxEntries       IngestionCapabilitiesMaxEntries       `json:"maxEntries"`
	MaxInteger       IngestionCapabilitiesMaxInteger       `json:"maxInteger"`
	MaxStringBytes   IngestionCapabilitiesMaxStringBytes   `json:"maxStringBytes"`
	ProtocolVersion  IngestionCapabilitiesProtocolVersion  `json:"protocolVersion"`
	SemanticsVersion IngestionCapabilitiesSemanticsVersion `json:"semanticsVersion"`
}

// IngestionCapabilitiesIdentityVersion defines model for IngestionCapabilities.IdentityVersion.
type IngestionCapabilitiesIdentityVersion int

// IngestionCapabilitiesMaxBodyBytes defines model for IngestionCapabilities.MaxBodyBytes.
type IngestionCapabilitiesMaxBodyBytes int

// IngestionCapabilitiesMaxEntries defines model for IngestionCapabilities.MaxEntries.
type IngestionCapabilitiesMaxEntries int

// IngestionCapabilitiesMaxInteger defines model for IngestionCapabilities.MaxInteger.
type IngestionCapabilitiesMaxInteger int64

// IngestionCapabilitiesMaxStringBytes defines model for IngestionCapabilities.MaxStringBytes.
type IngestionCapabilitiesMaxStringBytes int

// IngestionCapabilitiesProtocolVersion defines model for IngestionCapabilities.ProtocolVersion.
type IngestionCapabilitiesProtocolVersion int

// IngestionCapabilitiesSemanticsVersion defines model for IngestionCapabilities.SemanticsVersion.
type IngestionCapabilitiesSemanticsVersion int

// IngestionError Safe diagnostic codes and correlation IDs; request content is never echoed.
type IngestionError struct {
	// BatchId At most 256 UTF-8 bytes; no control characters.
	BatchId *string `json:"batchId,omitempty"`

	// Code At most 256 UTF-8 bytes; no control characters.
	Code string `json:"code"`

	// FactId At most 256 UTF-8 bytes; no control characters.
	FactId *string `json:"factId,omitempty"`

	// Stage At most 256 UTF-8 bytes; no control characters.
	Stage string `json:"stage"`
}

// IngestionReceipt Acknowledges the exact request hash after facts and receipt commit atomically. Counts sum to batch entry count. Exact batch replay returns the original receipt.
type IngestionReceipt struct {
	// BatchId At most 256 UTF-8 bytes; no control characters.
	BatchId       string `json:"batchId"`
	CommittedAtMs int64  `json:"committedAtMs"`

	// DatabaseId At most 256 UTF-8 bytes; no control characters.
	DatabaseId   string `json:"databaseId"`
	FromSequence int64  `json:"fromSequence"`
	Inserted     int64  `json:"inserted"`
	Noop         int64  `json:"noop"`

	// RequestHash At most 256 UTF-8 bytes; no control characters.
	RequestHash string `json:"requestHash"`
	Revision    int64  `json:"revision"`

	// StreamId At most 256 UTF-8 bytes; no control characters.
	StreamId   string `json:"streamId"`
	ToSequence int64  `json:"toSequence"`
	Updated    int64  `json:"updated"`
}

// InstanceResponse defines model for InstanceResponse.
type InstanceResponse struct {
	ApiVersion   ApiVersion   `json:"apiVersion"`
	Capabilities []Capability `json:"capabilities"`

	// DataEpoch Durable database identity; nonempty when dataReadiness is ready.
	DataEpoch     string                        `json:"dataEpoch"`
	DataReadiness InstanceResponseDataReadiness `json:"dataReadiness"`
	Defaults      Selection                     `json:"defaults"`

	// Hostname Producer hostname: unknown before ingestion; multiple machines when distinct producer labels are present.
	Hostname      string `json:"hostname"`
	InstanceId    string `json:"instanceId"`
	ServerVersion string `json:"serverVersion"`

	// Timezone Server reporting timezone, preferably an IANA name with historical DST rules. Unnamed system zones use an explicit UTC offset fallback.
	Timezone string `json:"timezone"`
}

// InstanceResponseDataReadiness defines model for InstanceResponse.DataReadiness.
type InstanceResponseDataReadiness string

// InstanceResponseV2 defines model for InstanceResponseV2.
type InstanceResponseV2 struct {
	ApiVersion   InstanceResponseV2ApiVersion `json:"apiVersion"`
	Capabilities []string                     `json:"capabilities"`

	// DataEpoch Durable database identity; nonempty when dataReadiness is ready.
	DataEpoch     string                          `json:"dataEpoch"`
	DataReadiness InstanceResponseV2DataReadiness `json:"dataReadiness"`
	DatasetId     string                          `json:"datasetId"`
	Defaults      Selection                       `json:"defaults"`

	// Hostname Producer hostname: unknown before ingestion; multiple machines when distinct producer labels are present.
	Hostname      string                          `json:"hostname"`
	InstanceId    string                          `json:"instanceId"`
	Permissions   []InstanceResponseV2Permissions `json:"permissions"`
	ServerKind    InstanceResponseV2ServerKind    `json:"serverKind"`
	ServerVersion string                          `json:"serverVersion"`

	// Timezone Server reporting timezone, preferably an IANA name with historical DST rules. Unnamed system zones use an explicit UTC offset fallback.
	Timezone string `json:"timezone"`
}

// InstanceResponseV2ApiVersion defines model for InstanceResponseV2.ApiVersion.
type InstanceResponseV2ApiVersion string

// InstanceResponseV2DataReadiness defines model for InstanceResponseV2.DataReadiness.
type InstanceResponseV2DataReadiness string

// InstanceResponseV2Permissions defines model for InstanceResponseV2.Permissions.
type InstanceResponseV2Permissions string

// InstanceResponseV2ServerKind defines model for InstanceResponseV2.ServerKind.
type InstanceResponseV2ServerKind string

// LocationGroup defines model for LocationGroup.
type LocationGroup string

// LocationOption defines model for LocationOption.
type LocationOption struct {
	Key string `json:"key"`

	// Name Sanitized display label; full source paths are never ingested.
	Name string `json:"name"`
}

// NativeScalar Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
type NativeScalar struct {
	union json.RawMessage
}

// NativeScalar0 defines model for NativeScalar.0.
type NativeScalar0 = string

// NativeScalar1 defines model for NativeScalar.1.
type NativeScalar1 = float32

// NativeScalar2 defines model for NativeScalar.2.
type NativeScalar2 = bool

// Period defines model for Period.
type Period string

// ProcessingStatus defines model for ProcessingStatus.
type ProcessingStatus struct {
	Generation    Count             `json:"generation"`
	InputRevision Count             `json:"inputRevision"`
	Items         []EvidenceOutcome `json:"items"`
	Pending       Count             `json:"pending"`
}

// PublicationBatch Immutable request bytes, at most 1 MiB. Entries form the contiguous inclusive sequence range. Database identity is obtained from capabilities. Unknown fields, duplicate JSON keys, null values, and non-integer numbers are rejected.
type PublicationBatch struct {
	// BatchId At most 256 UTF-8 bytes; no control characters.
	BatchId string `json:"batchId"`

	// DatabaseId At most 256 UTF-8 bytes; no control characters.
	DatabaseId   string             `json:"databaseId"`
	Entries      []PublicationEntry `json:"entries"`
	FromSequence int64              `json:"fromSequence"`

	// Hostname At most 256 UTF-8 bytes; no control characters.
	Hostname         *string                          `json:"hostname,omitempty"`
	IdentityVersion  PublicationBatchIdentityVersion  `json:"identityVersion"`
	ProtocolVersion  PublicationBatchProtocolVersion  `json:"protocolVersion"`
	SemanticsVersion PublicationBatchSemanticsVersion `json:"semanticsVersion"`

	// StreamId At most 256 UTF-8 bytes; no control characters.
	StreamId   string `json:"streamId"`
	ToSequence int64  `json:"toSequence"`
}

// PublicationBatchIdentityVersion defines model for PublicationBatch.IdentityVersion.
type PublicationBatchIdentityVersion int

// PublicationBatchProtocolVersion defines model for PublicationBatch.ProtocolVersion.
type PublicationBatchProtocolVersion int

// PublicationBatchSemanticsVersion defines model for PublicationBatch.SemanticsVersion.
type PublicationBatchSemanticsVersion int

// PublicationEntry defines model for PublicationEntry.
type PublicationEntry struct {
	// Fact IDs are recomputed from native identity tuples. A native message or request ID is required. Total equals the five token components. Session bounds include fact occurrence. Reference envelopes may merge; immutable payload changes conflict unless a supported source revision applies.
	Fact     PublicationFact `json:"fact"`
	Sequence int64           `json:"sequence"`
}

// PublicationFact IDs are recomputed from native identity tuples. A native message or request ID is required. Total equals the five token components. Session bounds include fact occurrence. Reference envelopes may merge; immutable payload changes conflict unless a supported source revision applies.
type PublicationFact struct {
	CacheReadTokens  int64   `json:"cacheReadTokens"`
	CacheWriteTokens int64   `json:"cacheWriteTokens"`
	Countable        bool    `json:"countable"`
	Harness          Harness `json:"harness"`

	// Id At most 256 UTF-8 bytes; no control characters.
	Id          string               `json:"id"`
	InputTokens int64                `json:"inputTokens"`
	Location    *PublicationLocation `json:"location,omitempty"`
	Message     *PublicationMessage  `json:"message,omitempty"`

	// Model At most 256 UTF-8 bytes; no control characters.
	Model string `json:"model"`

	// NativeRequestId At most 256 UTF-8 bytes; no control characters.
	NativeRequestId *string `json:"nativeRequestId,omitempty"`

	// OccurredAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	OccurredAtMs TimestampMs `json:"occurredAtMs"`
	OutputTokens int64       `json:"outputTokens"`

	// Provider At most 256 UTF-8 bytes; no control characters.
	Provider        string                        `json:"provider"`
	ProviderSource  PublicationFactProviderSource `json:"providerSource"`
	Quality         PublicationFactQuality        `json:"quality"`
	ReasoningTokens int64                         `json:"reasoningTokens"`

	// Revision Only Claude Code facts with native request and message IDs can carry this source timestamp revision; value equals occurredAtMs.
	Revision    *PublicationRevision      `json:"revision,omitempty"`
	Session     PublicationSession        `json:"session"`
	TotalTokens int64                     `json:"totalTokens"`
	UsageScope  PublicationFactUsageScope `json:"usageScope"`
}

// PublicationFactProviderSource defines model for PublicationFact.ProviderSource.
type PublicationFactProviderSource string

// PublicationFactQuality defines model for PublicationFact.Quality.
type PublicationFactQuality string

// PublicationFactUsageScope defines model for PublicationFact.UsageScope.
type PublicationFactUsageScope string

// PublicationLocation defines model for PublicationLocation.
type PublicationLocation struct {
	// DirectoryKey At most 256 UTF-8 bytes; no control characters.
	DirectoryKey *string `json:"directoryKey,omitempty"`

	// DirectoryName Sanitized basename label, at most 256 UTF-8 bytes; no path separators or control characters.
	DirectoryName *string `json:"directoryName,omitempty"`

	// Id At most 256 UTF-8 bytes; no control characters.
	Id string `json:"id"`

	// RepositoryKey At most 256 UTF-8 bytes; no control characters.
	RepositoryKey *string `json:"repositoryKey,omitempty"`

	// RepositoryName Sanitized basename label, at most 256 UTF-8 bytes; no path separators or control characters.
	RepositoryName *string `json:"repositoryName,omitempty"`

	// RepositorySource At most 256 UTF-8 bytes; no control characters.
	RepositorySource *string `json:"repositorySource,omitempty"`
}

// PublicationMessage defines model for PublicationMessage.
type PublicationMessage struct {
	// Id At most 256 UTF-8 bytes; no control characters.
	Id string `json:"id"`

	// NativeId At most 256 UTF-8 bytes; no control characters.
	NativeId string `json:"nativeId"`

	// OccurredAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	OccurredAtMs TimestampMs `json:"occurredAtMs"`
}

// PublicationRevision Only Claude Code facts with native request and message IDs can carry this source timestamp revision; value equals occurredAtMs.
type PublicationRevision struct {
	Rule PublicationRevisionRule `json:"rule"`

	// Value Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	Value TimestampMs `json:"value"`
}

// PublicationRevisionRule defines model for PublicationRevision.Rule.
type PublicationRevisionRule string

// PublicationSession defines model for PublicationSession.
type PublicationSession struct {
	// FirstOccurredAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	FirstOccurredAtMs TimestampMs `json:"firstOccurredAtMs"`
	Harness           Harness     `json:"harness"`

	// Id At most 256 UTF-8 bytes; no control characters.
	Id string `json:"id"`

	// LastOccurredAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	LastOccurredAtMs TimestampMs `json:"lastOccurredAtMs"`

	// NativeId At most 256 UTF-8 bytes; no control characters.
	NativeId string `json:"nativeId"`
}

// RawAcceptance defines model for RawAcceptance.
type RawAcceptance struct {
	Processing ProcessingStatus `json:"processing"`
	Receipt    RawReceipt       `json:"receipt"`
}

// RawAcceptanceV3 defines model for RawAcceptanceV3.
type RawAcceptanceV3 struct {
	Processing ProcessingStatus `json:"processing"`
	Receipt    RawReceiptV3     `json:"receipt"`
}

// RawBatch defines model for RawBatch.
type RawBatch struct {
	BatchId          string                   `json:"batchId"`
	DatabaseId       string                   `json:"databaseId"`
	Entries          []RawEntry               `json:"entries"`
	ExtractorVersion RawBatchExtractorVersion `json:"extractorVersion"`
	FromSequence     Count                    `json:"fromSequence"`
	ProtocolVersion  RawBatchProtocolVersion  `json:"protocolVersion"`
	StreamId         string                   `json:"streamId"`
	ToSequence       Count                    `json:"toSequence"`
}

// RawBatchExtractorVersion defines model for RawBatch.ExtractorVersion.
type RawBatchExtractorVersion int

// RawBatchProtocolVersion defines model for RawBatch.ProtocolVersion.
type RawBatchProtocolVersion int

// RawBatchV3 defines model for RawBatchV3.
type RawBatchV3 struct {
	BatchId          string                     `json:"batchId"`
	DatabaseId       string                     `json:"databaseId"`
	DatasetId        string                     `json:"datasetId"`
	Entries          []RawEntry                 `json:"entries"`
	ExtractorVersion RawBatchV3ExtractorVersion `json:"extractorVersion"`
	FromSequence     Count                      `json:"fromSequence"`
	ProtocolVersion  RawBatchV3ProtocolVersion  `json:"protocolVersion"`
	StreamId         string                     `json:"streamId"`
	ToSequence       Count                      `json:"toSequence"`
}

// RawBatchV3ExtractorVersion defines model for RawBatchV3.ExtractorVersion.
type RawBatchV3ExtractorVersion int

// RawBatchV3ProtocolVersion defines model for RawBatchV3.ProtocolVersion.
type RawBatchV3ProtocolVersion int

// RawCapabilities defines model for RawCapabilities.
type RawCapabilities struct {
	Completion       RawCapabilitiesCompletion       `json:"completion"`
	DatabaseId       string                          `json:"databaseId"`
	DatasetId        RawCapabilitiesDatasetId        `json:"datasetId"`
	ExtractorVersion RawCapabilitiesExtractorVersion `json:"extractorVersion"`
	MaxBodyBytes     RawCapabilitiesMaxBodyBytes     `json:"maxBodyBytes"`
	MaxEntries       RawCapabilitiesMaxEntries       `json:"maxEntries"`
	ProtocolVersion  RawCapabilitiesProtocolVersion  `json:"protocolVersion"`
}

// RawCapabilitiesCompletion defines model for RawCapabilities.Completion.
type RawCapabilitiesCompletion string

// RawCapabilitiesDatasetId defines model for RawCapabilities.DatasetId.
type RawCapabilitiesDatasetId string

// RawCapabilitiesExtractorVersion defines model for RawCapabilities.ExtractorVersion.
type RawCapabilitiesExtractorVersion int

// RawCapabilitiesMaxBodyBytes defines model for RawCapabilities.MaxBodyBytes.
type RawCapabilitiesMaxBodyBytes int

// RawCapabilitiesMaxEntries defines model for RawCapabilities.MaxEntries.
type RawCapabilitiesMaxEntries int

// RawCapabilitiesProtocolVersion defines model for RawCapabilities.ProtocolVersion.
type RawCapabilitiesProtocolVersion int

// RawCapabilitiesV3 defines model for RawCapabilitiesV3.
type RawCapabilitiesV3 struct {
	Completion       RawCapabilitiesV3Completion       `json:"completion"`
	DatabaseId       string                            `json:"databaseId"`
	DatasetId        string                            `json:"datasetId"`
	ExtractorVersion RawCapabilitiesV3ExtractorVersion `json:"extractorVersion"`
	MaxBodyBytes     RawCapabilitiesV3MaxBodyBytes     `json:"maxBodyBytes"`
	MaxEntries       RawCapabilitiesV3MaxEntries       `json:"maxEntries"`
	ProtocolVersion  RawCapabilitiesV3ProtocolVersion  `json:"protocolVersion"`
}

// RawCapabilitiesV3Completion defines model for RawCapabilitiesV3.Completion.
type RawCapabilitiesV3Completion string

// RawCapabilitiesV3ExtractorVersion defines model for RawCapabilitiesV3.ExtractorVersion.
type RawCapabilitiesV3ExtractorVersion int

// RawCapabilitiesV3MaxBodyBytes defines model for RawCapabilitiesV3.MaxBodyBytes.
type RawCapabilitiesV3MaxBodyBytes int

// RawCapabilitiesV3MaxEntries defines model for RawCapabilitiesV3.MaxEntries.
type RawCapabilitiesV3MaxEntries int

// RawCapabilitiesV3ProtocolVersion defines model for RawCapabilitiesV3.ProtocolVersion.
type RawCapabilitiesV3ProtocolVersion int

// RawContext defines model for RawContext.
type RawContext struct {
	// Data Only whitelisted scalar leaves and their containers. Allowed leaves further depend on harness and format; server validates the exact whitelist before storing any bytes.
	Data        RawSourceData           `json:"data"`
	Diagnostics *[]ExtractionDiagnostic `json:"diagnostics,omitempty"`
	Ordinal     Count                   `json:"ordinal"`
}

// RawEntry defines model for RawEntry.
type RawEntry struct {
	Record   RawRecord `json:"record"`
	Sequence Count     `json:"sequence"`
}

// RawLocation defines model for RawLocation.
type RawLocation struct {
	DirectoryKey     *string `json:"directoryKey,omitempty"`
	DirectoryName    *string `json:"directoryName,omitempty"`
	RepositoryKey    *string `json:"repositoryKey,omitempty"`
	RepositoryName   *string `json:"repositoryName,omitempty"`
	RepositorySource *string `json:"repositorySource,omitempty"`
}

// RawReceipt defines model for RawReceipt.
type RawReceipt struct {
	Accepted Count `json:"accepted"`

	// AcceptedAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	AcceptedAtMs  TimestampMs         `json:"acceptedAtMs"`
	BatchId       string              `json:"batchId"`
	DatabaseId    string              `json:"databaseId"`
	DatasetId     RawReceiptDatasetId `json:"datasetId"`
	FromSequence  Count               `json:"fromSequence"`
	InputRevision Count               `json:"inputRevision"`
	RequestHash   string              `json:"requestHash"`
	StreamId      string              `json:"streamId"`
	ToSequence    Count               `json:"toSequence"`
}

// RawReceiptDatasetId defines model for RawReceipt.DatasetId.
type RawReceiptDatasetId string

// RawReceiptV3 defines model for RawReceiptV3.
type RawReceiptV3 struct {
	Accepted Count `json:"accepted"`

	// AcceptedAtMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
	AcceptedAtMs  TimestampMs `json:"acceptedAtMs"`
	BatchId       string      `json:"batchId"`
	DatabaseId    string      `json:"databaseId"`
	DatasetId     string      `json:"datasetId"`
	FromSequence  Count       `json:"fromSequence"`
	InputRevision Count       `json:"inputRevision"`
	RequestHash   string      `json:"requestHash"`
	StreamId      string      `json:"streamId"`
	ToSequence    Count       `json:"toSequence"`
}

// RawRecord defines model for RawRecord.
type RawRecord struct {
	Context *[]RawContext `json:"context,omitempty"`

	// Data Only whitelisted scalar leaves and their containers. Allowed leaves further depend on harness and format; server validates the exact whitelist before storing any bytes.
	Data        RawSourceData           `json:"data"`
	Diagnostics *[]ExtractionDiagnostic `json:"diagnostics,omitempty"`
	Format      RawRecordFormat         `json:"format"`
	Harness     Harness                 `json:"harness"`
	Lineage     string                  `json:"lineage"`
	Location    *RawLocation            `json:"location,omitempty"`
	Ordinal     Count                   `json:"ordinal"`
	SourceId    string                  `json:"sourceId"`
}

// RawRecordFormat defines model for RawRecord.Format.
type RawRecordFormat string

// RawSourceData Only whitelisted scalar leaves and their containers. Allowed leaves further depend on harness and format; server validates the exact whitelist before storing any bytes.
type RawSourceData struct {
	Data *struct {
		Model *struct {
			// Id Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Id *NativeScalar `json:"id,omitempty"`

			// ProviderID Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			ProviderID *NativeScalar `json:"providerID,omitempty"`
		} `json:"model,omitempty"`

		// ModelID Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ModelID *NativeScalar `json:"modelID,omitempty"`

		// ProviderID Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ProviderID *NativeScalar `json:"providerID,omitempty"`

		// Role Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Role *NativeScalar `json:"role,omitempty"`
		Time *struct {
			// Completed Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Completed *NativeScalar `json:"completed,omitempty"`

			// Created Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Created *NativeScalar `json:"created,omitempty"`
		} `json:"time,omitempty"`
		Tokens *struct {
			Cache *struct {
				// Read Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				Read *NativeScalar `json:"read,omitempty"`

				// Write Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				Write *NativeScalar `json:"write,omitempty"`
			} `json:"cache,omitempty"`

			// Input Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Input *NativeScalar `json:"input,omitempty"`

			// Output Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Output *NativeScalar `json:"output,omitempty"`

			// Reasoning Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Reasoning *NativeScalar `json:"reasoning,omitempty"`
		} `json:"tokens,omitempty"`
	} `json:"data,omitempty"`

	// Id Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	Id      *NativeScalar `json:"id,omitempty"`
	Message *struct {
		// Id Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Id *NativeScalar `json:"id,omitempty"`

		// Model Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Model *NativeScalar `json:"model,omitempty"`

		// ModelID Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ModelID *NativeScalar `json:"modelID,omitempty"`

		// ModelIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ModelIdAlias *NativeScalar `json:"model_id,omitempty"`

		// Provider Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Provider *NativeScalar `json:"provider,omitempty"`

		// ProviderID Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ProviderID *NativeScalar `json:"providerID,omitempty"`

		// ProviderIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ProviderIdAlias *NativeScalar `json:"provider_id,omitempty"`

		// Role Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Role *NativeScalar `json:"role,omitempty"`

		// Timestamp Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Timestamp *NativeScalar `json:"timestamp,omitempty"`
		Usage     *struct {
			// CacheRead Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			CacheRead *NativeScalar `json:"cacheRead,omitempty"`

			// CacheWrite Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			CacheWrite *NativeScalar `json:"cacheWrite,omitempty"`

			// CacheCreationInputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			CacheCreationInputTokensAlias *NativeScalar `json:"cache_creation_input_tokens,omitempty"`

			// CacheReadInputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			CacheReadInputTokensAlias *NativeScalar `json:"cache_read_input_tokens,omitempty"`

			// Input Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Input *NativeScalar `json:"input,omitempty"`

			// InputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			InputTokensAlias *NativeScalar `json:"input_tokens,omitempty"`

			// Output Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Output *NativeScalar `json:"output,omitempty"`

			// OutputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			OutputTokensAlias        *NativeScalar `json:"output_tokens,omitempty"`
			OutputTokensDetailsAlias *struct {
				// ReasoningTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				ReasoningTokensAlias *NativeScalar `json:"reasoning_tokens,omitempty"`

				// ThinkingTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				ThinkingTokensAlias *NativeScalar `json:"thinking_tokens,omitempty"`
			} `json:"output_tokens_details,omitempty"`

			// Reasoning Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			Reasoning *NativeScalar `json:"reasoning,omitempty"`

			// TotalTokens Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			TotalTokens *NativeScalar `json:"totalTokens,omitempty"`

			// TotalTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
			TotalTokensAlias *NativeScalar `json:"total_tokens,omitempty"`
		} `json:"usage,omitempty"`
	} `json:"message,omitempty"`
	Payload *struct {
		// ForkedFromIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ForkedFromIdAlias *NativeScalar `json:"forked_from_id,omitempty"`

		// Id Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Id   *NativeScalar `json:"id,omitempty"`
		Info *struct {
			LastTokenUsageAlias *struct {
				// CacheReadInputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				CacheReadInputTokensAlias *NativeScalar `json:"cache_read_input_tokens,omitempty"`

				// CachedInputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				CachedInputTokensAlias *NativeScalar `json:"cached_input_tokens,omitempty"`

				// InputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				InputTokensAlias *NativeScalar `json:"input_tokens,omitempty"`

				// OutputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				OutputTokensAlias *NativeScalar `json:"output_tokens,omitempty"`

				// ReasoningOutputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				ReasoningOutputTokensAlias *NativeScalar `json:"reasoning_output_tokens,omitempty"`

				// TotalTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				TotalTokensAlias *NativeScalar `json:"total_tokens,omitempty"`
			} `json:"last_token_usage,omitempty"`
			TotalTokenUsageAlias *struct {
				// CacheReadInputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				CacheReadInputTokensAlias *NativeScalar `json:"cache_read_input_tokens,omitempty"`

				// CachedInputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				CachedInputTokensAlias *NativeScalar `json:"cached_input_tokens,omitempty"`

				// InputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				InputTokensAlias *NativeScalar `json:"input_tokens,omitempty"`

				// OutputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				OutputTokensAlias *NativeScalar `json:"output_tokens,omitempty"`

				// ReasoningOutputTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				ReasoningOutputTokensAlias *NativeScalar `json:"reasoning_output_tokens,omitempty"`

				// TotalTokensAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
				TotalTokensAlias *NativeScalar `json:"total_tokens,omitempty"`
			} `json:"total_token_usage,omitempty"`
		} `json:"info,omitempty"`

		// Model Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Model *NativeScalar `json:"model,omitempty"`

		// ModelProviderAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ModelProviderAlias *NativeScalar `json:"model_provider,omitempty"`

		// ParentThreadIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		ParentThreadIdAlias *NativeScalar `json:"parent_thread_id,omitempty"`
		Source              *struct {
			Subagent *struct {
				ThreadSpawnAlias *struct {
					// ParentThreadIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
					ParentThreadIdAlias *NativeScalar `json:"parent_thread_id,omitempty"`
				} `json:"thread_spawn,omitempty"`
			} `json:"subagent,omitempty"`
		} `json:"source,omitempty"`

		// TurnIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		TurnIdAlias *NativeScalar `json:"turn_id,omitempty"`

		// Type Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
		Type *NativeScalar `json:"type,omitempty"`
	} `json:"payload,omitempty"`

	// ProjectIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	ProjectIdAlias *NativeScalar `json:"project_id,omitempty"`

	// RequestId Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	RequestId *NativeScalar `json:"requestId,omitempty"`

	// RequestIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	RequestIdAlias *NativeScalar `json:"request_id,omitempty"`

	// SessionId Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	SessionId *NativeScalar `json:"sessionId,omitempty"`

	// SessionIdAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	SessionIdAlias *NativeScalar `json:"session_id,omitempty"`

	// TimeCreatedAlias Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	TimeCreatedAlias *NativeScalar `json:"time_created,omitempty"`

	// Timestamp Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	Timestamp *NativeScalar `json:"timestamp,omitempty"`

	// Type Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	Type *NativeScalar `json:"type,omitempty"`

	// Uuid Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	Uuid *NativeScalar `json:"uuid,omitempty"`

	// Vcs Original scalar source value, including explicit null. Processing validates integer counters and native timestamps.
	Vcs *NativeScalar `json:"vcs,omitempty"`
}

// ReprocessAcceptance defines model for ReprocessAcceptance.
type ReprocessAcceptance struct {
	Generation Count `json:"generation"`
}

// Selection defines model for Selection.
type Selection struct {
	Bucket Bucket `json:"bucket"`

	// From Inclusive lower local-date bound, or empty when unset.
	From      string    `json:"from"`
	Harnesses []Harness `json:"harnesses"`
	Models    []string  `json:"models"`
	Period    Period    `json:"period"`
	Providers []string  `json:"providers"`
	Sessions  []string  `json:"sessions"`

	// To Inclusive upper local-date bound, or empty when unset.
	To string `json:"to"`
}

// SortDirection defines model for SortDirection.
type SortDirection string

// SortField defines model for SortField.
type SortField string

// StatusResponseV2 defines model for StatusResponseV2.
type StatusResponseV2 struct {
	// DataEpoch Durable database identity; nonempty when dataReadiness is ready.
	DataEpoch        string                        `json:"dataEpoch"`
	DataReadiness    StatusResponseV2DataReadiness `json:"dataReadiness"`
	DatasetId        string                        `json:"datasetId"`
	Generation       Count                         `json:"generation"`
	InputRevision    Count                         `json:"inputRevision"`
	InstanceId       string                        `json:"instanceId"`
	Pending          Count                         `json:"pending"`
	Revision         Count                         `json:"revision"`
	TargetGeneration Count                         `json:"targetGeneration"`
}

// StatusResponseV2DataReadiness defines model for StatusResponseV2.DataReadiness.
type StatusResponseV2DataReadiness string

// SyncPhase defines model for SyncPhase.
type SyncPhase string

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	// DataEpoch Durable database identity; nonempty when dataReadiness is ready.
	DataEpoch     string                       `json:"dataEpoch"`
	DataReadiness SyncResponseDataReadiness    `json:"dataReadiness"`
	Error         string                       `json:"error"`
	Generation    *Count                       `json:"generation,omitempty"`
	Harnesses     map[string]HarnessSyncStatus `json:"harnesses"`
	InputRevision *Count                       `json:"inputRevision,omitempty"`
	InstanceId    string                       `json:"instanceId"`
	Pending       *Count                       `json:"pending,omitempty"`
	Phase         SyncPhase                    `json:"phase"`
	Revision      Count                        `json:"revision"`
	Running       bool                         `json:"running"`
}

// SyncResponseDataReadiness defines model for SyncResponse.DataReadiness.
type SyncResponseDataReadiness string

// TimestampMs Unix milliseconds through 9999-12-30T23:59:59.999Z. One day of headroom preserves calendar query support after timezone conversion. Source units are never guessed or rescaled.
type TimestampMs = int64

// UsageFacetsResponse defines model for UsageFacetsResponse.
type UsageFacetsResponse struct {
	DataEpoch     string           `json:"dataEpoch"`
	Directories   []LocationOption `json:"directories"`
	Generation    *Count           `json:"generation,omitempty"`
	Harnesses     []Harness        `json:"harnesses"`
	InputRevision *Count           `json:"inputRevision,omitempty"`
	InstanceId    string           `json:"instanceId"`
	Models        []string         `json:"models"`
	Pending       *Count           `json:"pending,omitempty"`
	Providers     []string         `json:"providers"`
	Repositories  []LocationOption `json:"repositories"`
	Revision      Count            `json:"revision"`
	Sessions      []string         `json:"sessions"`
}

// UsageFacetsResponseV2 defines model for UsageFacetsResponseV2.
type UsageFacetsResponseV2 struct {
	DataEpoch     string           `json:"dataEpoch"`
	DatasetId     string           `json:"datasetId"`
	Directories   []LocationOption `json:"directories"`
	Generation    *Count           `json:"generation,omitempty"`
	Harnesses     []Harness        `json:"harnesses"`
	InputRevision *Count           `json:"inputRevision,omitempty"`
	InstanceId    string           `json:"instanceId"`
	Models        []string         `json:"models"`
	Pending       *Count           `json:"pending,omitempty"`
	Providers     []string         `json:"providers"`
	Repositories  []LocationOption `json:"repositories"`
	Revision      Count            `json:"revision"`
	Sessions      []string         `json:"sessions"`
}

// UsageQuality Estimated evidence is queried separately and never included in confirmed totals.
type UsageQuality string

// UsageResponse defines model for UsageResponse.
type UsageResponse struct {
	Chart         []UsageRow `json:"chart"`
	DataEpoch     string     `json:"dataEpoch"`
	FactCount     *Count     `json:"factCount,omitempty"`
	Generation    *Count     `json:"generation,omitempty"`
	InputRevision *Count     `json:"inputRevision,omitempty"`
	InstanceId    string     `json:"instanceId"`

	// LastSynced Time of the last committed ingestion, in Unix milliseconds; zero for an empty server.
	LastSynced Count  `json:"lastSynced"`
	Page       int    `json:"page"`
	PageSize   int    `json:"pageSize"`
	Pending    *Count `json:"pending,omitempty"`

	// Quality Estimated evidence is queried separately and never included in confirmed totals.
	Quality    *UsageQuality `json:"quality,omitempty"`
	Range      string        `json:"range"`
	Revision   Count         `json:"revision"`
	RowCount   Count         `json:"rowCount"`
	Rows       []UsageRow    `json:"rows"`
	Summary    UsageSummary  `json:"summary"`
	Unresolved *Count        `json:"unresolved,omitempty"`
}

// UsageResponseV2 defines model for UsageResponseV2.
type UsageResponseV2 struct {
	Chart         []UsageRow `json:"chart"`
	DataEpoch     string     `json:"dataEpoch"`
	DatasetId     string     `json:"datasetId"`
	FactCount     *Count     `json:"factCount,omitempty"`
	Generation    *Count     `json:"generation,omitempty"`
	InputRevision *Count     `json:"inputRevision,omitempty"`
	InstanceId    string     `json:"instanceId"`

	// LastSynced Time of the last committed ingestion, in Unix milliseconds; zero for an empty server.
	LastSynced Count  `json:"lastSynced"`
	Page       int    `json:"page"`
	PageSize   int    `json:"pageSize"`
	Pending    *Count `json:"pending,omitempty"`

	// Quality Estimated evidence is queried separately and never included in confirmed totals.
	Quality    *UsageQuality `json:"quality,omitempty"`
	Range      string        `json:"range"`
	Revision   Count         `json:"revision"`
	RowCount   Count         `json:"rowCount"`
	Rows       []UsageRow    `json:"rows"`
	Summary    UsageSummary  `json:"summary"`
	Unresolved *Count        `json:"unresolved,omitempty"`
}

// UsageRow defines model for UsageRow.
type UsageRow struct {
	AverageContext Count `json:"averageContext"`
	CacheRead      Count `json:"cacheRead"`
	CacheWrite     Count `json:"cacheWrite"`
	Context        Count `json:"context"`
	Date           Count `json:"date"`

	// DirectoryNames Distinct recorded directories contributing to this row, sorted by display name. Empty outside Repo rows.
	DirectoryNames []string `json:"directoryNames"`
	Harness        string   `json:"harness"`

	// HasUnknownDirectory Whether any contributing fact lacks a recorded directory. False outside Repo rows.
	HasUnknownDirectory bool   `json:"hasUnknownDirectory"`
	Input               Count  `json:"input"`
	Key                 string `json:"key"`
	LocationKey         string `json:"locationKey"`

	// LocationName Sanitized display label; full source paths are never ingested.
	LocationName   string `json:"locationName"`
	MaxContext     Count  `json:"maxContext"`
	MedianContext  Count  `json:"medianContext"`
	Model          string `json:"model"`
	Name           string `json:"name"`
	Output         Count  `json:"output"`
	Provider       string `json:"provider"`
	Reasoning      Count  `json:"reasoning"`
	RepositoryKey  string `json:"repositoryKey"`
	RepositoryName string `json:"repositoryName"`
	Sessions       Count  `json:"sessions"`
	Total          Count  `json:"total"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	CacheRead      Count `json:"cacheRead"`
	CacheWrite     Count `json:"cacheWrite"`
	Input          Count `json:"input"`
	Output         Count `json:"output"`
	Reasoning      Count `json:"reasoning"`
	Sessions       Count `json:"sessions"`
	SyncedSessions Count `json:"syncedSessions"`
	Total          Count `json:"total"`
}

// UsageTab defines model for UsageTab.
type UsageTab string

// BucketFilter defines model for BucketFilter.
type BucketFilter = Bucket

// DirectoryFilter defines model for DirectoryFilter.
type DirectoryFilter = []string

// FromFilter defines model for FromFilter.
type FromFilter = string

// HarnessFilter defines model for HarnessFilter.
type HarnessFilter = []Harness

// ModelFilter defines model for ModelFilter.
type ModelFilter = []string

// PeriodFilter defines model for PeriodFilter.
type PeriodFilter = Period

// ProviderFilter defines model for ProviderFilter.
type ProviderFilter = []string

// QualityFilter Estimated evidence is queried separately and never included in confirmed totals.
type QualityFilter = UsageQuality

// RepositoryFilter defines model for RepositoryFilter.
type RepositoryFilter = []string

// SessionFilter defines model for SessionFilter.
type SessionFilter = []string

// ToFilter defines model for ToFilter.
type ToFilter = string

// Error defines model for Error.
type Error = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// Unavailable defines model for Unavailable.
type Unavailable = ErrorResponse

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	Period *PeriodFilter `form:"period,omitempty" json:"period,omitempty"`
	Bucket *BucketFilter `form:"bucket,omitempty" json:"bucket,omitempty"`

	// From Inclusive lower local-date bound; replaces period when supplied.
	From *FromFilter `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper local-date bound; replaces period when supplied.
	To *ToFilter `form:"to,omitempty" json:"to,omitempty"`

	// Provider Provider filter. Repeat the parameter to select multiple values.
	Provider *ProviderFilter `form:"provider,omitempty" json:"provider,omitempty"`

	// Model Model filter. Repeat the parameter to select multiple values.
	Model *ModelFilter `form:"model,omitempty" json:"model,omitempty"`

	// Harness Harness filter. Repeat the parameter to select multiple values.
	Harness *HarnessFilter `form:"harness,omitempty" json:"harness,omitempty"`

	// Session Session-ID filter. Repeat the parameter to select multiple values.
	Session *SessionFilter `form:"session,omitempty" json:"session,omitempty"`

	// Repository Repo-tab stable repository key; repeat for multiple values. The key unknown selects missing values.
	Repository *RepositoryFilter `form:"repository,omitempty" json:"repository,omitempty"`

	// Directory Repo-tab stable directory key; repeat for multiple values. The key unknown selects missing values.
	Directory *DirectoryFilter `form:"directory,omitempty" json:"directory,omitempty"`

	// Tab Aggregation shown in table and chart rows.
	Tab *UsageTab `form:"tab,omitempty" json:"tab,omitempty"`

	// LocationGroup Repo-tab grouping by repository or directory.
	LocationGroup *LocationGroup `form:"locationGroup,omitempty" json:"locationGroup,omitempty"`

	// Sort Sort field. Context-only fields are valid only for the context tab.
	Sort      *SortField     `form:"sort,omitempty" json:"sort,omitempty"`
	Direction *SortDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Page      *int           `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Quality   *QualityFilter `form:"quality,omitempty" json:"quality,omitempty"`
}

// GetUsageFacetsParams defines parameters for GetUsageFacets.
type GetUsageFacetsParams struct {
	Period *PeriodFilter `form:"period,omitempty" json:"period,omitempty"`
	Bucket *BucketFilter `form:"bucket,omitempty" json:"bucket,omitempty"`

	// From Inclusive lower local-date bound; replaces period when supplied.
	From *FromFilter `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper local-date bound; replaces period when supplied.
	To *ToFilter `form:"to,omitempty" json:"to,omitempty"`

	// Provider Provider filter. Repeat the parameter to select multiple values.
	Provider *ProviderFilter `form:"provider,omitempty" json:"provider,omitempty"`

	// Model Model filter. Repeat the parameter to select multiple values.
	Model *ModelFilter `form:"model,omitempty" json:"model,omitempty"`

	// Harness Harness filter. Repeat the parameter to select multiple values.
	Harness *HarnessFilter `form:"harness,omitempty" json:"harness,omitempty"`

	// Session Session-ID filter. Repeat the parameter to select multiple values.
	Session *SessionFilter `form:"session,omitempty" json:"session,omitempty"`

	// Repository Repo-tab stable repository key; repeat for multiple values. The key unknown selects missing values.
	Repository *RepositoryFilter `form:"repository,omitempty" json:"repository,omitempty"`

	// Directory Repo-tab stable directory key; repeat for multiple values. The key unknown selects missing values.
	Directory *DirectoryFilter `form:"directory,omitempty" json:"directory,omitempty"`

	// Search Literal substring used to filter session IDs.
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Tab Active aggregation. Repository/directory filters require the repo tab.
	Tab     *UsageTab      `form:"tab,omitempty" json:"tab,omitempty"`
	Quality *QualityFilter `form:"quality,omitempty" json:"quality,omitempty"`
}

// GetUsageV2Params defines parameters for GetUsageV2.
type GetUsageV2Params struct {
	Period *PeriodFilter `form:"period,omitempty" json:"period,omitempty"`
	Bucket *BucketFilter `form:"bucket,omitempty" json:"bucket,omitempty"`

	// From Inclusive lower local-date bound; replaces period when supplied.
	From *FromFilter `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper local-date bound; replaces period when supplied.
	To *ToFilter `form:"to,omitempty" json:"to,omitempty"`

	// Provider Provider filter. Repeat the parameter to select multiple values.
	Provider *ProviderFilter `form:"provider,omitempty" json:"provider,omitempty"`

	// Model Model filter. Repeat the parameter to select multiple values.
	Model *ModelFilter `form:"model,omitempty" json:"model,omitempty"`

	// Harness Harness filter. Repeat the parameter to select multiple values.
	Harness *HarnessFilter `form:"harness,omitempty" json:"harness,omitempty"`

	// Session Session-ID filter. Repeat the parameter to select multiple values.
	Session *SessionFilter `form:"session,omitempty" json:"session,omitempty"`

	// Repository Repo-tab stable repository key; repeat for multiple values. The key unknown selects missing values.
	Repository *RepositoryFilter `form:"repository,omitempty" json:"repository,omitempty"`

	// Directory Repo-tab stable directory key; repeat for multiple values. The key unknown selects missing values.
	Directory *DirectoryFilter `form:"directory,omitempty" json:"directory,omitempty"`

	// Tab Aggregation shown in table and chart rows.
	Tab *UsageTab `form:"tab,omitempty" json:"tab,omitempty"`

	// LocationGroup Repo-tab grouping by repository or directory.
	LocationGroup *LocationGroup `form:"locationGroup,omitempty" json:"locationGroup,omitempty"`

	// Sort Sort field. Context-only fields are valid only for the context tab.
	Sort      *SortField     `form:"sort,omitempty" json:"sort,omitempty"`
	Direction *SortDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Page      *int           `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Quality   *QualityFilter `form:"quality,omitempty" json:"quality,omitempty"`
}

// GetUsageFacetsV2Params defines parameters for GetUsageFacetsV2.
type GetUsageFacetsV2Params struct {
	Period *PeriodFilter `form:"period,omitempty" json:"period,omitempty"`
	Bucket *BucketFilter `form:"bucket,omitempty" json:"bucket,omitempty"`

	// From Inclusive lower local-date bound; replaces period when supplied.
	From *FromFilter `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper local-date bound; replaces period when supplied.
	To *ToFilter `form:"to,omitempty" json:"to,omitempty"`

	// Provider Provider filter. Repeat the parameter to select multiple values.
	Provider *ProviderFilter `form:"provider,omitempty" json:"provider,omitempty"`

	// Model Model filter. Repeat the parameter to select multiple values.
	Model *ModelFilter `form:"model,omitempty" json:"model,omitempty"`

	// Harness Harness filter. Repeat the parameter to select multiple values.
	Harness *HarnessFilter `form:"harness,omitempty" json:"harness,omitempty"`

	// Session Session-ID filter. Repeat the parameter to select multiple values.
	Session *SessionFilter `form:"session,omitempty" json:"session,omitempty"`

	// Repository Repo-tab stable repository key; repeat for multiple values. The key unknown selects missing values.
	Repository *RepositoryFilter `form:"repository,omitempty" json:"repository,omitempty"`

	// Directory Repo-tab stable directory key; repeat for multiple values. The key unknown selects missing values.
	Directory *DirectoryFilter `form:"directory,omitempty" json:"directory,omitempty"`

	// Search Literal substring used to filter session IDs.
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Tab Active aggregation. Repository/directory filters require the repo tab.
	Tab     *UsageTab      `form:"tab,omitempty" json:"tab,omitempty"`
	Quality *QualityFilter `form:"quality,omitempty" json:"quality,omitempty"`
}

// IngestBatchJSONRequestBody defines body for IngestBatch for application/json ContentType.
//
// Deprecated: this type has been marked as deprecated upstream, but no `x-deprecated-reason` was set
type IngestBatchJSONRequestBody = PublicationBatch

// CreateBrowserSessionJSONRequestBody defines body for CreateBrowserSession for application/json ContentType.
type CreateBrowserSessionJSONRequestBody = BrowserSessionRequest

// IngestRawBatchJSONRequestBody defines body for IngestRawBatch for application/json ContentType.
type IngestRawBatchJSONRequestBody = RawBatch

// IngestRawBatchV3JSONRequestBody defines body for IngestRawBatchV3 for application/json ContentType.
type IngestRawBatchV3JSONRequestBody = RawBatchV3

// AsNativeScalar0 returns the union data inside the NativeScalar as a NativeScalar0
func (t NativeScalar) AsNativeScalar0() (NativeScalar0, error) {
	var body NativeScalar0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNativeScalar0 overwrites any union data inside the NativeScalar as the provided NativeScalar0
func (t *NativeScalar) FromNativeScalar0(v NativeScalar0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNativeScalar0 performs a merge with any union data inside the NativeScalar, using the provided NativeScalar0
func (t *NativeScalar) MergeNativeScalar0(v NativeScalar0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNativeScalar1 returns the union data inside the NativeScalar as a NativeScalar1
func (t NativeScalar) AsNativeScalar1() (NativeScalar1, error) {
	var body NativeScalar1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNativeScalar1 overwrites any union data inside the NativeScalar as the provided NativeScalar1
func (t *NativeScalar) FromNativeScalar1(v NativeScalar1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNativeScalar1 performs a merge with any union data inside the NativeScalar, using the provided NativeScalar1
func (t *NativeScalar) MergeNativeScalar1(v NativeScalar1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNativeScalar2 returns the union data inside the NativeScalar as a NativeScalar2
func (t NativeScalar) AsNativeScalar2() (NativeScalar2, error) {
	var body NativeScalar2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNativeScalar2 overwrites any union data inside the NativeScalar as the provided NativeScalar2
func (t *NativeScalar) FromNativeScalar2(v NativeScalar2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNativeScalar2 performs a merge with any union data inside the NativeScalar, using the provided NativeScalar2
func (t *NativeScalar) MergeNativeScalar2(v NativeScalar2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NativeScalar) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NativeScalar) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
