// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// Defines values for ApiVersion.
const (
	V1 ApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the ApiVersion enum.
func (e ApiVersion) Valid() bool {
	switch e {
	case V1:
		return true
	default:
		return false
	}
}

// Defines values for Bucket.
const (
	BucketDay   Bucket = "day"
	BucketMonth Bucket = "month"
	BucketWeek  Bucket = "week"
	BucketYear  Bucket = "year"
)

// Valid indicates whether the value is a known member of the Bucket enum.
func (e Bucket) Valid() bool {
	switch e {
	case BucketDay:
		return true
	case BucketMonth:
		return true
	case BucketWeek:
		return true
	case BucketYear:
		return true
	default:
		return false
	}
}

// Defines values for Capability.
const (
	Facets    Capability = "facets"
	Ingestion Capability = "ingestion"
	Usage     Capability = "usage"
)

// Valid indicates whether the value is a known member of the Capability enum.
func (e Capability) Valid() bool {
	switch e {
	case Facets:
		return true
	case Ingestion:
		return true
	case Usage:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeInternalError    ErrorCode = "internal_error"
	ErrorCodeInvalidRequest   ErrorCode = "invalid_request"
	ErrorCodeMethodNotAllowed ErrorCode = "method_not_allowed"
	ErrorCodeNotFound         ErrorCode = "not_found"
	ErrorCodeUnavailable      ErrorCode = "unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeMethodNotAllowed:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for Harness.
const (
	ClaudeCode Harness = "claude-code"
	Codex      Harness = "codex"
	Opencode   Harness = "opencode"
	Pi         Harness = "pi"
)

// Valid indicates whether the value is a known member of the Harness enum.
func (e Harness) Valid() bool {
	switch e {
	case ClaudeCode:
		return true
	case Codex:
		return true
	case Opencode:
		return true
	case Pi:
		return true
	default:
		return false
	}
}

// Defines values for HarnessSyncStatus.
const (
	Discovering HarnessSyncStatus = "discovering"
	Failed      HarnessSyncStatus = "failed"
	Normalizing HarnessSyncStatus = "normalizing"
	Pending     HarnessSyncStatus = "pending"
	Skipped     HarnessSyncStatus = "skipped"
	Synced      HarnessSyncStatus = "synced"
	Syncing     HarnessSyncStatus = "syncing"
)

// Valid indicates whether the value is a known member of the HarnessSyncStatus enum.
func (e HarnessSyncStatus) Valid() bool {
	switch e {
	case Discovering:
		return true
	case Failed:
		return true
	case Normalizing:
		return true
	case Pending:
		return true
	case Skipped:
		return true
	case Synced:
		return true
	case Syncing:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesIdentityVersion.
const (
	IngestionCapabilitiesIdentityVersionN1 IngestionCapabilitiesIdentityVersion = 1
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesIdentityVersion enum.
func (e IngestionCapabilitiesIdentityVersion) Valid() bool {
	switch e {
	case IngestionCapabilitiesIdentityVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxBodyBytes.
const (
	N1048576e06 IngestionCapabilitiesMaxBodyBytes = 1.048576e+06
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxBodyBytes enum.
func (e IngestionCapabilitiesMaxBodyBytes) Valid() bool {
	switch e {
	case N1048576e06:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxEntries.
const (
	IngestionCapabilitiesMaxEntriesN256 IngestionCapabilitiesMaxEntries = 256
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxEntries enum.
func (e IngestionCapabilitiesMaxEntries) Valid() bool {
	switch e {
	case IngestionCapabilitiesMaxEntriesN256:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxInteger.
const (
	N9007199254740991e15 IngestionCapabilitiesMaxInteger = 9.007199254740991e+15
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxInteger enum.
func (e IngestionCapabilitiesMaxInteger) Valid() bool {
	switch e {
	case N9007199254740991e15:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesMaxStringBytes.
const (
	IngestionCapabilitiesMaxStringBytesN256 IngestionCapabilitiesMaxStringBytes = 256
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesMaxStringBytes enum.
func (e IngestionCapabilitiesMaxStringBytes) Valid() bool {
	switch e {
	case IngestionCapabilitiesMaxStringBytesN256:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesProtocolVersion.
const (
	IngestionCapabilitiesProtocolVersionN1 IngestionCapabilitiesProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesProtocolVersion enum.
func (e IngestionCapabilitiesProtocolVersion) Valid() bool {
	switch e {
	case IngestionCapabilitiesProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for IngestionCapabilitiesSemanticsVersion.
const (
	IngestionCapabilitiesSemanticsVersionN1 IngestionCapabilitiesSemanticsVersion = 1
)

// Valid indicates whether the value is a known member of the IngestionCapabilitiesSemanticsVersion enum.
func (e IngestionCapabilitiesSemanticsVersion) Valid() bool {
	switch e {
	case IngestionCapabilitiesSemanticsVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for InstanceResponseDataReadiness.
const (
	InstanceResponseDataReadinessMetadata    InstanceResponseDataReadiness = "metadata"
	InstanceResponseDataReadinessReady       InstanceResponseDataReadiness = "ready"
	InstanceResponseDataReadinessRebuild     InstanceResponseDataReadiness = "rebuild"
	InstanceResponseDataReadinessRecovery    InstanceResponseDataReadiness = "recovery"
	InstanceResponseDataReadinessUnavailable InstanceResponseDataReadiness = "unavailable"
)

// Valid indicates whether the value is a known member of the InstanceResponseDataReadiness enum.
func (e InstanceResponseDataReadiness) Valid() bool {
	switch e {
	case InstanceResponseDataReadinessMetadata:
		return true
	case InstanceResponseDataReadinessReady:
		return true
	case InstanceResponseDataReadinessRebuild:
		return true
	case InstanceResponseDataReadinessRecovery:
		return true
	case InstanceResponseDataReadinessUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for LocationGroup.
const (
	Directory  LocationGroup = "directory"
	Repository LocationGroup = "repository"
)

// Valid indicates whether the value is a known member of the LocationGroup enum.
func (e LocationGroup) Valid() bool {
	switch e {
	case Directory:
		return true
	case Repository:
		return true
	default:
		return false
	}
}

// Defines values for Period.
const (
	PeriodAll       Period = "all"
	PeriodMonth     Period = "month"
	PeriodToday     Period = "today"
	PeriodWeek      Period = "week"
	PeriodYear      Period = "year"
	PeriodYesterday Period = "yesterday"
)

// Valid indicates whether the value is a known member of the Period enum.
func (e Period) Valid() bool {
	switch e {
	case PeriodAll:
		return true
	case PeriodMonth:
		return true
	case PeriodToday:
		return true
	case PeriodWeek:
		return true
	case PeriodYear:
		return true
	case PeriodYesterday:
		return true
	default:
		return false
	}
}

// Defines values for PublicationBatchIdentityVersion.
const (
	PublicationBatchIdentityVersionN1 PublicationBatchIdentityVersion = 1
)

// Valid indicates whether the value is a known member of the PublicationBatchIdentityVersion enum.
func (e PublicationBatchIdentityVersion) Valid() bool {
	switch e {
	case PublicationBatchIdentityVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for PublicationBatchProtocolVersion.
const (
	PublicationBatchProtocolVersionN1 PublicationBatchProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the PublicationBatchProtocolVersion enum.
func (e PublicationBatchProtocolVersion) Valid() bool {
	switch e {
	case PublicationBatchProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for PublicationBatchSemanticsVersion.
const (
	PublicationBatchSemanticsVersionN1 PublicationBatchSemanticsVersion = 1
)

// Valid indicates whether the value is a known member of the PublicationBatchSemanticsVersion enum.
func (e PublicationBatchSemanticsVersion) Valid() bool {
	switch e {
	case PublicationBatchSemanticsVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for PublicationFactProviderSource.
const (
	Explicit PublicationFactProviderSource = "explicit"
	Inferred PublicationFactProviderSource = "inferred"
	Unknown  PublicationFactProviderSource = "unknown"
)

// Valid indicates whether the value is a known member of the PublicationFactProviderSource enum.
func (e PublicationFactProviderSource) Valid() bool {
	switch e {
	case Explicit:
		return true
	case Inferred:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for PublicationFactQuality.
const (
	Derived   PublicationFactQuality = "derived"
	Estimated PublicationFactQuality = "estimated"
	Exact     PublicationFactQuality = "exact"
)

// Valid indicates whether the value is a known member of the PublicationFactQuality enum.
func (e PublicationFactQuality) Valid() bool {
	switch e {
	case Derived:
		return true
	case Estimated:
		return true
	case Exact:
		return true
	default:
		return false
	}
}

// Defines values for PublicationFactUsageScope.
const (
	Message PublicationFactUsageScope = "message"
)

// Valid indicates whether the value is a known member of the PublicationFactUsageScope enum.
func (e PublicationFactUsageScope) Valid() bool {
	switch e {
	case Message:
		return true
	default:
		return false
	}
}

// Defines values for PublicationRevisionRule.
const (
	ClaudeSourceTimestampV1 PublicationRevisionRule = "claude-source-timestamp-v1"
)

// Valid indicates whether the value is a known member of the PublicationRevisionRule enum.
func (e PublicationRevisionRule) Valid() bool {
	switch e {
	case ClaudeSourceTimestampV1:
		return true
	default:
		return false
	}
}

// Defines values for SortDirection.
const (
	Asc  SortDirection = "asc"
	Desc SortDirection = "desc"
)

// Valid indicates whether the value is a known member of the SortDirection enum.
func (e SortDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for SortField.
const (
	SortFieldAverageContext SortField = "averageContext"
	SortFieldCacheRead      SortField = "cacheRead"
	SortFieldCacheWrite     SortField = "cacheWrite"
	SortFieldContext        SortField = "context"
	SortFieldDate           SortField = "date"
	SortFieldHarness        SortField = "harness"
	SortFieldInput          SortField = "input"
	SortFieldMaxContext     SortField = "maxContext"
	SortFieldMedianContext  SortField = "medianContext"
	SortFieldModel          SortField = "model"
	SortFieldName           SortField = "name"
	SortFieldOutput         SortField = "output"
	SortFieldProvider       SortField = "provider"
	SortFieldReasoning      SortField = "reasoning"
	SortFieldSessions       SortField = "sessions"
	SortFieldTotal          SortField = "total"
)

// Valid indicates whether the value is a known member of the SortField enum.
func (e SortField) Valid() bool {
	switch e {
	case SortFieldAverageContext:
		return true
	case SortFieldCacheRead:
		return true
	case SortFieldCacheWrite:
		return true
	case SortFieldContext:
		return true
	case SortFieldDate:
		return true
	case SortFieldHarness:
		return true
	case SortFieldInput:
		return true
	case SortFieldMaxContext:
		return true
	case SortFieldMedianContext:
		return true
	case SortFieldModel:
		return true
	case SortFieldName:
		return true
	case SortFieldOutput:
		return true
	case SortFieldProvider:
		return true
	case SortFieldReasoning:
		return true
	case SortFieldSessions:
		return true
	case SortFieldTotal:
		return true
	default:
		return false
	}
}

// Defines values for SyncPhase.
const (
	SyncPhaseReady SyncPhase = "ready"
)

// Valid indicates whether the value is a known member of the SyncPhase enum.
func (e SyncPhase) Valid() bool {
	switch e {
	case SyncPhaseReady:
		return true
	default:
		return false
	}
}

// Defines values for SyncResponseDataReadiness.
const (
	SyncResponseDataReadinessMetadata    SyncResponseDataReadiness = "metadata"
	SyncResponseDataReadinessReady       SyncResponseDataReadiness = "ready"
	SyncResponseDataReadinessRebuild     SyncResponseDataReadiness = "rebuild"
	SyncResponseDataReadinessRecovery    SyncResponseDataReadiness = "recovery"
	SyncResponseDataReadinessUnavailable SyncResponseDataReadiness = "unavailable"
)

// Valid indicates whether the value is a known member of the SyncResponseDataReadiness enum.
func (e SyncResponseDataReadiness) Valid() bool {
	switch e {
	case SyncResponseDataReadinessMetadata:
		return true
	case SyncResponseDataReadinessReady:
		return true
	case SyncResponseDataReadinessRebuild:
		return true
	case SyncResponseDataReadinessRecovery:
		return true
	case SyncResponseDataReadinessUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for UsageTab.
const (
	UsageTabContext   UsageTab = "context"
	UsageTabHarnesses UsageTab = "harnesses"
	UsageTabModels    UsageTab = "models"
	UsageTabProviders UsageTab = "providers"
	UsageTabRepo      UsageTab = "repo"
	UsageTabSessions  UsageTab = "sessions"
	UsageTabTokens    UsageTab = "tokens"
)

// Valid indicates whether the value is a known member of the UsageTab enum.
func (e UsageTab) Valid() bool {
	switch e {
	case UsageTabContext:
		return true
	case UsageTabHarnesses:
		return true
	case UsageTabModels:
		return true
	case UsageTabProviders:
		return true
	case UsageTabRepo:
		return true
	case UsageTabSessions:
		return true
	case UsageTabTokens:
		return true
	default:
		return false
	}
}

// ApiVersion defines model for ApiVersion.
type ApiVersion string

// Bucket defines model for Bucket.
type Bucket string

// Capability defines model for Capability.
type Capability string

// Count defines model for Count.
type Count = int64

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// Harness defines model for Harness.
type Harness string

// HarnessSyncStatus defines model for HarnessSyncStatus.
type HarnessSyncStatus string

// IngestionCapabilities defines model for IngestionCapabilities.
type IngestionCapabilities struct {
	// DatabaseId At most 256 UTF-8 bytes; no control characters.
	DatabaseId       string                                `json:"databaseId"`
	IdentityVersion  IngestionCapabilitiesIdentityVersion  `json:"identityVersion"`
	MaxBodyBytes     IngestionCapabilitiesMaxBodyBytes     `json:"maxBodyBytes"`
	MaxEntries       IngestionCapabilitiesMaxEntries       `json:"maxEntries"`
	MaxInteger       IngestionCapabilitiesMaxInteger       `json:"maxInteger"`
	MaxStringBytes   IngestionCapabilitiesMaxStringBytes   `json:"maxStringBytes"`
	ProtocolVersion  IngestionCapabilitiesProtocolVersion  `json:"protocolVersion"`
	SemanticsVersion IngestionCapabilitiesSemanticsVersion `json:"semanticsVersion"`
}

// IngestionCapabilitiesIdentityVersion defines model for IngestionCapabilities.IdentityVersion.
type IngestionCapabilitiesIdentityVersion int

// IngestionCapabilitiesMaxBodyBytes defines model for IngestionCapabilities.MaxBodyBytes.
type IngestionCapabilitiesMaxBodyBytes int

// IngestionCapabilitiesMaxEntries defines model for IngestionCapabilities.MaxEntries.
type IngestionCapabilitiesMaxEntries int

// IngestionCapabilitiesMaxInteger defines model for IngestionCapabilities.MaxInteger.
type IngestionCapabilitiesMaxInteger int64

// IngestionCapabilitiesMaxStringBytes defines model for IngestionCapabilities.MaxStringBytes.
type IngestionCapabilitiesMaxStringBytes int

// IngestionCapabilitiesProtocolVersion defines model for IngestionCapabilities.ProtocolVersion.
type IngestionCapabilitiesProtocolVersion int

// IngestionCapabilitiesSemanticsVersion defines model for IngestionCapabilities.SemanticsVersion.
type IngestionCapabilitiesSemanticsVersion int

// IngestionError Safe diagnostic codes and correlation IDs; request content is never echoed.
type IngestionError struct {
	// BatchId At most 256 UTF-8 bytes; no control characters.
	BatchId *string `json:"batchId,omitempty"`

	// Code At most 256 UTF-8 bytes; no control characters.
	Code string `json:"code"`

	// FactId At most 256 UTF-8 bytes; no control characters.
	FactId *string `json:"factId,omitempty"`

	// Stage At most 256 UTF-8 bytes; no control characters.
	Stage string `json:"stage"`
}

// IngestionReceipt Acknowledges the exact request hash after facts and receipt commit atomically. Counts sum to batch entry count. Exact batch replay returns the original receipt.
type IngestionReceipt struct {
	// BatchId At most 256 UTF-8 bytes; no control characters.
	BatchId       string `json:"batchId"`
	CommittedAtMs int64  `json:"committedAtMs"`

	// DatabaseId At most 256 UTF-8 bytes; no control characters.
	DatabaseId   string `json:"databaseId"`
	FromSequence int64  `json:"fromSequence"`
	Inserted     int64  `json:"inserted"`
	Noop         int64  `json:"noop"`

	// RequestHash At most 256 UTF-8 bytes; no control characters.
	RequestHash string `json:"requestHash"`
	Revision    int64  `json:"revision"`

	// StreamId At most 256 UTF-8 bytes; no control characters.
	StreamId   string `json:"streamId"`
	ToSequence int64  `json:"toSequence"`
	Updated    int64  `json:"updated"`
}

// InstanceResponse defines model for InstanceResponse.
type InstanceResponse struct {
	ApiVersion    ApiVersion                     `json:"apiVersion"`
	Capabilities  []Capability                   `json:"capabilities"`
	DataEpoch     *string                        `json:"dataEpoch,omitempty"`
	DataReadiness *InstanceResponseDataReadiness `json:"dataReadiness,omitempty"`
	Defaults      Selection                      `json:"defaults"`

	// Hostname Producer hostname: unknown before ingestion; multiple machines when distinct producer labels are present.
	Hostname      string  `json:"hostname"`
	InstanceId    *string `json:"instanceId,omitempty"`
	ServerVersion string  `json:"serverVersion"`

	// Timezone Server reporting timezone, preferably an IANA name with historical DST rules. Unnamed system zones use an explicit UTC offset fallback.
	Timezone string `json:"timezone"`
}

// InstanceResponseDataReadiness defines model for InstanceResponse.DataReadiness.
type InstanceResponseDataReadiness string

// LocationGroup defines model for LocationGroup.
type LocationGroup string

// LocationOption defines model for LocationOption.
type LocationOption struct {
	Key string `json:"key"`

	// Name Sanitized display label; full source paths are never ingested.
	Name string `json:"name"`
}

// Period defines model for Period.
type Period string

// PublicationBatch Immutable request bytes, at most 1 MiB. Entries form the contiguous inclusive sequence range. Database identity is obtained from capabilities. Unknown fields, duplicate JSON keys, null values, and non-integer numbers are rejected.
type PublicationBatch struct {
	// BatchId At most 256 UTF-8 bytes; no control characters.
	BatchId string `json:"batchId"`

	// DatabaseId At most 256 UTF-8 bytes; no control characters.
	DatabaseId   string             `json:"databaseId"`
	Entries      []PublicationEntry `json:"entries"`
	FromSequence int64              `json:"fromSequence"`

	// Hostname At most 256 UTF-8 bytes; no control characters.
	Hostname         *string                          `json:"hostname,omitempty"`
	IdentityVersion  PublicationBatchIdentityVersion  `json:"identityVersion"`
	ProtocolVersion  PublicationBatchProtocolVersion  `json:"protocolVersion"`
	SemanticsVersion PublicationBatchSemanticsVersion `json:"semanticsVersion"`

	// StreamId At most 256 UTF-8 bytes; no control characters.
	StreamId   string `json:"streamId"`
	ToSequence int64  `json:"toSequence"`
}

// PublicationBatchIdentityVersion defines model for PublicationBatch.IdentityVersion.
type PublicationBatchIdentityVersion int

// PublicationBatchProtocolVersion defines model for PublicationBatch.ProtocolVersion.
type PublicationBatchProtocolVersion int

// PublicationBatchSemanticsVersion defines model for PublicationBatch.SemanticsVersion.
type PublicationBatchSemanticsVersion int

// PublicationEntry defines model for PublicationEntry.
type PublicationEntry struct {
	// Fact IDs are recomputed from native identity tuples. A native message or request ID is required. Total equals the five token components. Session bounds include fact occurrence. Reference envelopes may merge; immutable payload changes conflict unless a supported source revision applies.
	Fact     PublicationFact `json:"fact"`
	Sequence int64           `json:"sequence"`
}

// PublicationFact IDs are recomputed from native identity tuples. A native message or request ID is required. Total equals the five token components. Session bounds include fact occurrence. Reference envelopes may merge; immutable payload changes conflict unless a supported source revision applies.
type PublicationFact struct {
	CacheReadTokens  int64   `json:"cacheReadTokens"`
	CacheWriteTokens int64   `json:"cacheWriteTokens"`
	Countable        bool    `json:"countable"`
	Harness          Harness `json:"harness"`

	// Id At most 256 UTF-8 bytes; no control characters.
	Id          string               `json:"id"`
	InputTokens int64                `json:"inputTokens"`
	Location    *PublicationLocation `json:"location,omitempty"`
	Message     *PublicationMessage  `json:"message,omitempty"`

	// Model At most 256 UTF-8 bytes; no control characters.
	Model string `json:"model"`

	// NativeRequestId At most 256 UTF-8 bytes; no control characters.
	NativeRequestId *string `json:"nativeRequestId,omitempty"`
	OccurredAtMs    int64   `json:"occurredAtMs"`
	OutputTokens    int64   `json:"outputTokens"`

	// Provider At most 256 UTF-8 bytes; no control characters.
	Provider        string                        `json:"provider"`
	ProviderSource  PublicationFactProviderSource `json:"providerSource"`
	Quality         PublicationFactQuality        `json:"quality"`
	ReasoningTokens int64                         `json:"reasoningTokens"`

	// Revision Only Claude Code facts with native request and message IDs can carry this source timestamp revision; value equals occurredAtMs.
	Revision    *PublicationRevision      `json:"revision,omitempty"`
	Session     PublicationSession        `json:"session"`
	TotalTokens int64                     `json:"totalTokens"`
	UsageScope  PublicationFactUsageScope `json:"usageScope"`
}

// PublicationFactProviderSource defines model for PublicationFact.ProviderSource.
type PublicationFactProviderSource string

// PublicationFactQuality defines model for PublicationFact.Quality.
type PublicationFactQuality string

// PublicationFactUsageScope defines model for PublicationFact.UsageScope.
type PublicationFactUsageScope string

// PublicationLocation defines model for PublicationLocation.
type PublicationLocation struct {
	// DirectoryKey At most 256 UTF-8 bytes; no control characters.
	DirectoryKey *string `json:"directoryKey,omitempty"`

	// DirectoryName Sanitized basename label, at most 256 UTF-8 bytes; no path separators or control characters.
	DirectoryName *string `json:"directoryName,omitempty"`

	// Id At most 256 UTF-8 bytes; no control characters.
	Id string `json:"id"`

	// RepositoryKey At most 256 UTF-8 bytes; no control characters.
	RepositoryKey *string `json:"repositoryKey,omitempty"`

	// RepositoryName Sanitized basename label, at most 256 UTF-8 bytes; no path separators or control characters.
	RepositoryName *string `json:"repositoryName,omitempty"`

	// RepositorySource At most 256 UTF-8 bytes; no control characters.
	RepositorySource *string `json:"repositorySource,omitempty"`
}

// PublicationMessage defines model for PublicationMessage.
type PublicationMessage struct {
	// Id At most 256 UTF-8 bytes; no control characters.
	Id string `json:"id"`

	// NativeId At most 256 UTF-8 bytes; no control characters.
	NativeId     string `json:"nativeId"`
	OccurredAtMs int64  `json:"occurredAtMs"`
}

// PublicationRevision Only Claude Code facts with native request and message IDs can carry this source timestamp revision; value equals occurredAtMs.
type PublicationRevision struct {
	Rule  PublicationRevisionRule `json:"rule"`
	Value int64                   `json:"value"`
}

// PublicationRevisionRule defines model for PublicationRevision.Rule.
type PublicationRevisionRule string

// PublicationSession defines model for PublicationSession.
type PublicationSession struct {
	FirstOccurredAtMs int64   `json:"firstOccurredAtMs"`
	Harness           Harness `json:"harness"`

	// Id At most 256 UTF-8 bytes; no control characters.
	Id               string `json:"id"`
	LastOccurredAtMs int64  `json:"lastOccurredAtMs"`

	// NativeId At most 256 UTF-8 bytes; no control characters.
	NativeId string `json:"nativeId"`
}

// Selection defines model for Selection.
type Selection struct {
	Bucket Bucket `json:"bucket"`

	// From Inclusive lower local-date bound, or empty when unset.
	From      string    `json:"from"`
	Harnesses []Harness `json:"harnesses"`
	Models    []string  `json:"models"`
	Period    Period    `json:"period"`
	Providers []string  `json:"providers"`
	Sessions  []string  `json:"sessions"`

	// To Inclusive upper local-date bound, or empty when unset.
	To string `json:"to"`
}

// SortDirection defines model for SortDirection.
type SortDirection string

// SortField defines model for SortField.
type SortField string

// SyncPhase defines model for SyncPhase.
type SyncPhase string

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	DataEpoch     *string                      `json:"dataEpoch,omitempty"`
	DataReadiness *SyncResponseDataReadiness   `json:"dataReadiness,omitempty"`
	Error         string                       `json:"error"`
	Harnesses     map[string]HarnessSyncStatus `json:"harnesses"`
	InstanceId    *string                      `json:"instanceId,omitempty"`
	Phase         SyncPhase                    `json:"phase"`
	Revision      Count                        `json:"revision"`
	Running       bool                         `json:"running"`
}

// SyncResponseDataReadiness defines model for SyncResponse.DataReadiness.
type SyncResponseDataReadiness string

// UsageFacetsResponse defines model for UsageFacetsResponse.
type UsageFacetsResponse struct {
	DataEpoch    *string          `json:"dataEpoch,omitempty"`
	Directories  []LocationOption `json:"directories"`
	Harnesses    []Harness        `json:"harnesses"`
	InstanceId   *string          `json:"instanceId,omitempty"`
	Models       []string         `json:"models"`
	Providers    []string         `json:"providers"`
	Repositories []LocationOption `json:"repositories"`
	Revision     *Count           `json:"revision,omitempty"`
	Sessions     []string         `json:"sessions"`
}

// UsageResponse defines model for UsageResponse.
type UsageResponse struct {
	Chart      []UsageRow `json:"chart"`
	DataEpoch  *string    `json:"dataEpoch,omitempty"`
	InstanceId *string    `json:"instanceId,omitempty"`

	// LastSynced Time of the last committed ingestion, in Unix milliseconds; zero for an empty server.
	LastSynced Count        `json:"lastSynced"`
	Page       int          `json:"page"`
	PageSize   int          `json:"pageSize"`
	Range      string       `json:"range"`
	Revision   *Count       `json:"revision,omitempty"`
	RowCount   Count        `json:"rowCount"`
	Rows       []UsageRow   `json:"rows"`
	Summary    UsageSummary `json:"summary"`
}

// UsageRow defines model for UsageRow.
type UsageRow struct {
	AverageContext Count `json:"averageContext"`
	CacheRead      Count `json:"cacheRead"`
	CacheWrite     Count `json:"cacheWrite"`
	Context        Count `json:"context"`
	Date           Count `json:"date"`

	// DirectoryNames Distinct recorded directories contributing to this row, sorted by display name. Empty outside Repo rows.
	DirectoryNames []string `json:"directoryNames"`
	Harness        string   `json:"harness"`

	// HasUnknownDirectory Whether any contributing fact lacks a recorded directory. False outside Repo rows.
	HasUnknownDirectory bool   `json:"hasUnknownDirectory"`
	Input               Count  `json:"input"`
	Key                 string `json:"key"`
	LocationKey         string `json:"locationKey"`

	// LocationName Sanitized display label; full source paths are never ingested.
	LocationName   string `json:"locationName"`
	MaxContext     Count  `json:"maxContext"`
	MedianContext  Count  `json:"medianContext"`
	Model          string `json:"model"`
	Name           string `json:"name"`
	Output         Count  `json:"output"`
	Provider       string `json:"provider"`
	Reasoning      Count  `json:"reasoning"`
	RepositoryKey  string `json:"repositoryKey"`
	RepositoryName string `json:"repositoryName"`
	Sessions       Count  `json:"sessions"`
	Total          Count  `json:"total"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	CacheRead      Count `json:"cacheRead"`
	CacheWrite     Count `json:"cacheWrite"`
	Input          Count `json:"input"`
	Output         Count `json:"output"`
	Reasoning      Count `json:"reasoning"`
	Sessions       Count `json:"sessions"`
	SyncedSessions Count `json:"syncedSessions"`
	Total          Count `json:"total"`
}

// UsageTab defines model for UsageTab.
type UsageTab string

// BucketFilter defines model for BucketFilter.
type BucketFilter = Bucket

// DirectoryFilter defines model for DirectoryFilter.
type DirectoryFilter = []string

// FromFilter defines model for FromFilter.
type FromFilter = string

// HarnessFilter defines model for HarnessFilter.
type HarnessFilter = []Harness

// ModelFilter defines model for ModelFilter.
type ModelFilter = []string

// PeriodFilter defines model for PeriodFilter.
type PeriodFilter = Period

// ProviderFilter defines model for ProviderFilter.
type ProviderFilter = []string

// RepositoryFilter defines model for RepositoryFilter.
type RepositoryFilter = []string

// SessionFilter defines model for SessionFilter.
type SessionFilter = []string

// ToFilter defines model for ToFilter.
type ToFilter = string

// Error defines model for Error.
type Error = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// Unavailable defines model for Unavailable.
type Unavailable = ErrorResponse

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	Period *PeriodFilter `form:"period,omitempty" json:"period,omitempty"`
	Bucket *BucketFilter `form:"bucket,omitempty" json:"bucket,omitempty"`

	// From Inclusive lower local-date bound; replaces period when supplied.
	From *FromFilter `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper local-date bound; replaces period when supplied.
	To *ToFilter `form:"to,omitempty" json:"to,omitempty"`

	// Provider Provider filter. Repeat the parameter to select multiple values.
	Provider *ProviderFilter `form:"provider,omitempty" json:"provider,omitempty"`

	// Model Model filter. Repeat the parameter to select multiple values.
	Model *ModelFilter `form:"model,omitempty" json:"model,omitempty"`

	// Harness Harness filter. Repeat the parameter to select multiple values.
	Harness *HarnessFilter `form:"harness,omitempty" json:"harness,omitempty"`

	// Session Session-ID filter. Repeat the parameter to select multiple values.
	Session *SessionFilter `form:"session,omitempty" json:"session,omitempty"`

	// Repository Repo-tab stable repository key; repeat for multiple values. The key unknown selects missing values.
	Repository *RepositoryFilter `form:"repository,omitempty" json:"repository,omitempty"`

	// Directory Repo-tab stable directory key; repeat for multiple values. The key unknown selects missing values.
	Directory *DirectoryFilter `form:"directory,omitempty" json:"directory,omitempty"`

	// Tab Aggregation shown in table and chart rows.
	Tab *UsageTab `form:"tab,omitempty" json:"tab,omitempty"`

	// LocationGroup Repo-tab grouping by repository or directory.
	LocationGroup *LocationGroup `form:"locationGroup,omitempty" json:"locationGroup,omitempty"`

	// Sort Sort field. Context-only fields are valid only for the context tab.
	Sort      *SortField     `form:"sort,omitempty" json:"sort,omitempty"`
	Direction *SortDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Page      *int           `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetUsageFacetsParams defines parameters for GetUsageFacets.
type GetUsageFacetsParams struct {
	Period *PeriodFilter `form:"period,omitempty" json:"period,omitempty"`
	Bucket *BucketFilter `form:"bucket,omitempty" json:"bucket,omitempty"`

	// From Inclusive lower local-date bound; replaces period when supplied.
	From *FromFilter `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper local-date bound; replaces period when supplied.
	To *ToFilter `form:"to,omitempty" json:"to,omitempty"`

	// Provider Provider filter. Repeat the parameter to select multiple values.
	Provider *ProviderFilter `form:"provider,omitempty" json:"provider,omitempty"`

	// Model Model filter. Repeat the parameter to select multiple values.
	Model *ModelFilter `form:"model,omitempty" json:"model,omitempty"`

	// Harness Harness filter. Repeat the parameter to select multiple values.
	Harness *HarnessFilter `form:"harness,omitempty" json:"harness,omitempty"`

	// Session Session-ID filter. Repeat the parameter to select multiple values.
	Session *SessionFilter `form:"session,omitempty" json:"session,omitempty"`

	// Repository Repo-tab stable repository key; repeat for multiple values. The key unknown selects missing values.
	Repository *RepositoryFilter `form:"repository,omitempty" json:"repository,omitempty"`

	// Directory Repo-tab stable directory key; repeat for multiple values. The key unknown selects missing values.
	Directory *DirectoryFilter `form:"directory,omitempty" json:"directory,omitempty"`

	// Search Literal substring used to filter session IDs.
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Tab Active aggregation. Repository/directory filters require the repo tab.
	Tab *UsageTab `form:"tab,omitempty" json:"tab,omitempty"`
}

// IngestBatchJSONRequestBody defines body for IngestBatch for application/json ContentType.
type IngestBatchJSONRequestBody = PublicationBatch
