package db

const (
	TableIngestRuns               = "ingest_runs"
	TableRawTokenUsage            = "raw_token_usage"
	TableRawObservations          = "raw_observations"
	TableNormalizationWorkQueue   = "normalization_work_queue"
	TableSourceRefreshState       = "source_refresh_state"
	TableCanonicalSessions        = "canonical_sessions"
	TableCanonicalMessages        = "canonical_messages"
	TableCanonicalTokenUsage      = "canonical_token_usage"
	TableNormalizationDiagnostics = "normalization_diagnostics"
)

const (
	ColID               = "id"
	ColRunID            = "run_id"
	ColHarness          = "harness"
	ColCollector        = "collector"
	ColParser           = "parser"
	ColSourceID         = "source_id"
	ColSourceKind       = "source_kind"
	ColStatus           = "status"
	ColStartedAtMs      = "started_at_ms"
	ColCompletedAtMs    = "completed_at_ms"
	ColErrorMessage     = "error_message"
	ColRawFactCount     = "raw_fact_count"
	ColObservationCount = "observation_count"
	ColCanonicalCount   = "canonical_count"
	ColDiagnosticCount  = "diagnostic_count"
	ColRawFactKey       = "raw_fact_key"
	ColObservedAtMs     = "observed_at_ms"
	ColOccurredAtMs     = "occurred_at_ms"
	ColSessionID        = "session_id"
	ColMessageID        = "message_id"
	ColProvider         = "provider"
	ColProviderSource   = "provider_source"
	ColModel            = "model"
	ColUsageScope       = "usage_scope"
	ColQuality          = "quality"
	ColInputTokens      = "input_tokens"
	ColOutputTokens     = "output_tokens"
	ColReasoningTokens  = "reasoning_tokens"
	ColCacheReadTokens  = "cache_read_tokens"
	ColCacheWriteTokens = "cache_write_tokens"
	ColTotalTokens      = "total_tokens"
	ColMetadataJSON     = "metadata_json"
	ColIngestRunID      = "ingest_run_id"
	ColRawFactID        = "raw_fact_id"
	ColDomain           = "domain"
	ColEnqueuedAtMs     = "enqueued_at_ms"
	ColSourceStateKey   = "source_state_key"
	ColLastRefreshAtMs  = "last_successful_refresh_at_ms"
	ColSourceMtimeMs    = "source_mtime_ms"
	ColSourceSizeBytes  = "source_size_bytes"
	ColUpdatedAtMs      = "updated_at_ms"
	ColObservationKey   = "observation_key"
	ColSemanticKey      = "semantic_key"
	ColFirstSeenAtMs    = "first_seen_at_ms"
	ColLastSeenAtMs     = "last_seen_at_ms"
	ColPrimaryRawFactID = "primary_raw_fact_id"
	ColHarnessMessageID = "harness_message_id"
	ColRecordedAtMs     = "recorded_at_ms"
	ColIsCountable      = "is_countable"
	ColDiagnosticKey    = "diagnostic_key"
	ColSeverity         = "severity"
	ColCode             = "code"
	ColMessage          = "message"
)

const SupportedSchemaVersion = 7
